### ISSUE TITLE
Review CanRetrieveAllDeployKeys test

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1003]
There seems to be a rule here in the vein of "you can't use that SSH key for deployment, it's already been added" - given the rule is based on a static public key from `ssh-keygen`, create a new key in the test might be a bit challenging to do - open to suggestions about how to tackle this.

Also relates to #533 because there are other muted tests in here.

**Comment by Haacked** [comment]
> create a new key in the test might be a bit challenging to do

Why is that? My brain had a core dump and I don't retain any context at all about this code path. :stuck_out_tongue:

**Comment by shiftkey** [comment]
@haacked we'd need a way to emulate this sort of operation:

```
> ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
```

**Comment by ryangribble** [comment]
Hey so as part of working on fixing #1106 I came across this skipped test.

At work we use [Chillkat.net](https://www.nuget.org/packages/chilkat-x64) ([x64](https://www.nuget.org/packages/chilkat-x64) [x86](https://www.nuget.org/packages/chilkat-win32/)) when we need to generate SSH keys in c# code...

Im not sure if nuget packages work on linux/OSX builds, but then it seems like the Integration Tests dont run on those platforms anyway right?  So would chillkat be a viable option?

Let me know if I should pursue this...

My plan would be to add chillkat nuget reference to ```Octokit.Integration.Tests``` project, and use it to create helper context extension method ```GitHubClient.CreatePublicKeyContext``` to create a public key and delete it again when going out of scope.  Then I should be able to re-enable this test and things should be pretty reliable as we wont trip over any issues if keys still existed from previous runs, since we'd be creating a new key everytime (and also cleaning it up, unless anything goes wrong)

**Comment by Haacked** [comment]
Sounds good to me. @shiftkey?

**Comment by shiftkey** [comment]
@Haacked @ryangribble definitely worth exploring - I stumbled upon it a while ago but got sad at the fact it wasn't OSS. I also have some reservations about the [licensing](http://www.chilkatsoft.com/licensingExplained.asp) of the components (having been bitten by this in the past) but let's see what comes up.

**Comment by Haacked** [comment]
> I stumbled upon it a while ago but got sad at the fact it wasn't OSS. I also have some reservations about the licensing of the components (having been bitten by this in the past) but let's see what comes up.

Ah, that could be problematic.

**Comment by ryangribble** [comment]
I'll try to find what license pertains to their freeware libraries, like the SSH one I'm referring to 
http://www.chilkatsoft.com/sshkey-features.asp
