### ISSUE TITLE
Implement Enterprise - Search Indexing client

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1026]
New in Enterprise 2.4

https://developer.github.com/v3/enterprise/search_indexing/

```
/enterprise/search_indexing/
 - POST /staff/indexing_jobs
```

**Comment by ryangribble** [comment]
Im going to take this one  too

Question: Given the various options that are passed in to this API call as "target" parameter, what would be the preferred approach?  I was thinking of creating individual methods for the various options...  I haven't found a similar API elsewhere yet, though Im not familiar with the entire API.

```
Target						Description
:owner						A user or organization account.
:owner/:repository			A repository.
:owner/*					All of a user or organization's repositories.
:owner/:repository/issues	All the issues in a repository.
:owner/*/issues				All the issues in all of a user or organization's repositories.
:owner/:repository/code		All the source code in a repository.
:owner/*/code				All the source code in all of a user or organization's repositories.
```
So my proposal would be to create functions similar to:

```
Enterprise.SearchIndexing.QueueOwner(string owner)
Enterprise.SearchIndexing.QueueRepository(string owner, string repository)
Enterprise.SearchIndexing.QueueAllRepositoriesForOwner(string owner)
Enterprise.SearchIndexing.QueueAllIssuesForRepository(string owner, string repository)
Enterprise.SearchIndexing.QueueAllIssuesForOwner(string owner)
Enterprise.SearchIndexing.QueueAllCodeForRepository(string owner, string repository)
Enterprise.SearchIndexing.QueueAllCodeForOwner(string owner)
```

Sound OK?

**Comment by ryangribble** [comment]
Or another approach would be to have a single method with overrides for owner, or owner+repo, and an enum to specify the scoping

```
Enterprise.SearchIndexing.QueueJob(string owner, IndexTypeOwner indexType)
Enterprise.SearchIndexing.QueueJob(string owner, string repository, IndexTypeRepository indexType)

enum IndexTypeOwner
{
Owner,
AllOwnedRepositories,
AllIssues,
AllCode
}

enum IndexTypeRepository
{
Repository,
AllIssues,
AllCode
}
```

:question:

**Comment by shiftkey** [comment]
@ryangribble the first snippet could be distilled down to this:

```
Enterprise.SearchIndexing.Queue(string owner)
Enterprise.SearchIndexing.Queue(string owner, string repository)
Enterprise.SearchIndexing.QueueAll(string owner)
Enterprise.SearchIndexing.QueueAllIssues(string owner, string repository)
Enterprise.SearchIndexing.QueueAllIssues(string owner)
Enterprise.SearchIndexing.QueueAllCode(string owner, string repository)
Enterprise.SearchIndexing.QueueAllCode(string owner)
```

But the second could also work. Happy to go with whatever feels natural once you're writing the plumbing inside the client.

**Comment by ryangribble** [comment]
So I implemented most of this last night, your distilled version felt pretty natural @shiftkey 

The only "fun" thing so far is that the "single" queue actions (like owner and repo) endpoints return a single "message" response element like
```
{
   "message":"User \"ryan-gribble\" was added to the indexing queue"
}
```


Whilst the other "QueueAll" type endpoints return an array of messages, like 

```
{
   "message":[
      "Repository \"ryan-gribble/public-repo-20160202020400602\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202022240540\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202022354531\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023154471\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023156249\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023157339\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023331579\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023433230\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023434613\" was added to the indexing queue",
      "Repository \"ryan-gribble/public-repo-20160202023435691\" was added to the indexing queue"
   ]
}
```

It looks like the json parser does handle deserializing the single message element into the response model class with ```IReadOnlyList<string> Message``` however it also "eats" the dash character in my username, resulting in
```User "ryangribble" was added to the indexing queue```
Rather than
```User "ryan-gribble" was added to the indexing queue```

So do you think I should implement 2 different response classes, one for single actions and one for multiple actions... or attempt to figure out/fix why the serializer is "eating" the hyphen?!
@shiftkey ?

**Comment by shiftkey** [comment]
> however it also "eats" the dash character in my username, resulting in

![](https://cloud.githubusercontent.com/assets/359239/12767919/392f43be-ca5c-11e5-8149-bf4f9e4ef5a5.gif)

> So do you think I should implement 2 different response classes, one for single actions and one for multiple actions... or attempt to figure out/fix why the serializer is "eating" the hyphen?!

Ideally, I'd like to deal with the latter - are you able to isolate this in a test to the deserializer step? (i.e. just use the JSON and try to deserialize to the list)

**Comment by ryangribble** [comment]
:+1: ok will take a look tonight

**Comment by ryangribble** [comment]
Yep a failing test like this shows the problem.  

```
[Fact]
            public void DoesntEatHyphensForBreakfast()
            {
                const string data = @"{""message"":""my-test-string""}";
                var httpResponse = new Response(
                    HttpStatusCode.OK,
                    data,
                    new Dictionary<string, string>(),
                    "application/json");
                var jsonPipeline = new JsonHttpPipeline();

                var response = jsonPipeline.DeserializeResponse<SearchIndexingResponse>(httpResponse);
                Assert.Equal("my-test-string", response.Body.Message[0]);
                // Fails due to returned value "myteststring"
            }
```

Ill either fix it, or raise an issue and Ignore the test (noting the issue number).  Just want to finish off implementing this SearchIndexing api first

**Comment by ryangribble** [comment]
So the responsible line is https://github.com/octokit/octokit.net/blob/master/Octokit/Http/SimpleJsonSerializer.cs#L93
```stringValue = stringValue.Replace("-", "");```

Looking at when it was added on PR #727 https://github.com/janovesk/octokit.net/commit/46e572131f7175b3a85a6a86d62b139c49d22111 ...
It looks to me like the problem of handling underscores in enum values should be taken care of by the ```RemoveHyphenAndUnderscore(stringValue)``` calls added for Enum and nullable Enum types, so im not sure why the first ```stringValue = stringValue.Replace("-", "");``` was also introduced.  

I removed line 93 and unit tests are passing, just running integration tests now... though there's always the risk that not enough tests around this area exist.

**Comment by shiftkey** [comment]
@ryangribble excellent find! I'll look over that PR to see if I can understand why we might have done that.

> I removed line 93 and unit tests are passing, just running integration tests now... though there's always the risk that not enough tests around this area exist.

I can also look over the integration tests as part of this review, to sanity check things...

**Comment by ryangribble** [comment]
Yep, I removed the line and all current unit and integration tests passed, including the ones for property values with underscores added back in that PR, so it's a good sign. 

Of course if we don't have test coverage for every scenario we may miss something, but the best way to handle that IMO is to add tests if/when something breaks. Judging by the existing tests it looks like there's been a good culture of adhering to that approach, so one assumes the tests we currently have already assert behaviour complies with any previous reported shenanigans. 

This situation was a pretty out lying  edge case I guess, attempting to deserialize a string into a IReadonlyList<string> (due to previous comment regarding differences in the message response from queueing a single item vs queueing all repositl/issues/whatever) 

Would you rather handle this json deserialize hyphen problem on a new issue/PR or shall I include it in this one? 

As an aside it seems some of the integration tests (unrelated to this change) aren't consistently passing first time, but do pass after one or more retries so I might flag that for follow up ad well

**Comment by shiftkey** [comment]
> Would you rather handle this json deserialize hyphen problem on a new issue/PR or shall I include it in this one?

I'd like to address that in isolation, so a separate PR would be :sparkles:

**Comment by ryangribble** [comment]
Done (#1094) and also completed this Search Indexing API (#1095)
