### ISSUE TITLE
Pulling out JSON parser

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1074]
The premise for this question is as follows:
I am working on a project template for visual studio that will make it easier to create API wrappers ala octoki.net
As I was getting familiar with the project and code structure used, I noticed that the JSON parsing is done by a few small classes internal to octokit.
I am mainly refering to [this file](https://github.com/octokit/octokit.net/blob/master/Octokit%2FHttp%2FSimpleJsonSerializer.cs)

Is the parser something that is decoupled enough that it could be separated into a separate project?
Collaries:
- I am not asking you to do it
- It may not make sense for octokit to remove it and re-include it as  dependency - but it could be useful for other people
- Even if it is not something that can live _fully_ on it's own, there is still a question on whether copying those classes would work

as an aside - why would anyone need/use yet another json parser? A: It can be billed as lightweight and designed specifically for use with APIs

**Comment by shiftkey** [comment]
> Is the parser something that is decoupled enough that it could be separated into a separate project?

It's tied to SimpleJson, which we use as an internal dependency. We've submitted some patches upstream to `SimpleJson.cs`, but `SimpleJsonSerializer` is the hooks for us to control how to serialize and deserialize objects in the context of Octokit.

For me, I guess it comes down to whether you're happy with how you're using the current Octokit APIs, or whether there's a different way (or abstraction?) you'd like to use. Then we could talk about extracting the models and serialization logic - I gather that's the bit you're really interested in here, rather than just the JSON pieces.

One such scenario that I need to flesh out is consuming webhooks - I'd want to reuse the models (and thus the deserialization rules) we already have, but how they plug into an MVC app is very different.

> as an aside - why would anyone need/use yet another json parser? 

We avoid paying the JSON.NET tax here by internalizing our JSON logic, and while you *can* plug in [your own serializer](https://github.com/octokit/octokit.net/blob/master/Octokit/Http/Connection.cs#L50) it's deep in the bowels of Octokit, so I wouldn't worry about needing to do that...

**Comment by M-Zuber** [comment]
Thank you for responding. Apologies if I was not clear enough. 
I'm asking about the serializer **not** in the context of octokit.net. 
For example there is [this api](http://beta.pokeapi.co/docsv2/) which has no wrappers. I would like to create one modeled after the octokit way. 
Since there are multiple such apis, a project template with the folder structure setup would be nice. 
In order to make it even better, I want to include code wherever it makes sense. 

So the json parser + serialization being internal don't bother me - but how simple do you think it would be to copy out the code and dump it into a project with different models?

**Comment by shiftkey** [comment]
@M-Zuber it's all good, happy to talk further about it

> So the json parser + serialization being internal don't bother me - but how simple do you think it would be to copy out the code and dump it into a project with different models?

I don't think it'd be much work - I'm pretty sure someone has repurposed this codebase (or been inspired by it) to apply it to a different sort of API. I forget the product, it came through via Twitter.

The serializer rules are kind of tweaked to what the GitHub API expects - but it's nothing special.

Here's a bit of a brain dump of some of the more quirky features on offer beyond that: 

 - with request models, `null` values are not sent by default
 - you opt into those with a `[SerializeNull]` attribute
 - managing the formatting of properties when serializing/deserializing - server expects Ruby style (like `review_comment_url`) and client expects .NET style (like `ReviewCommentUrl`)
 - a few different ways to override this when deserializing - e.g. enum serialization, map JSON property to different response
 - converting text to base64 when sending is done through `[SerializeAsBase64]` so the user doesn't care about the implementation details

I'm :thumbsup: if someone wants to extract these relevant bits and explore making it more general purpose for API clients.

**Comment by M-Zuber** [comment]
>I'm pretty sure someone has repurposed this codebase (or been inspired by it) to apply it to a different sort of API. I forget the product, it came through via Twitter.

It may very well have been me :grinning:, as I have been sitting on this for a long time

>I'm :thumbsup: if someone wants to extract these relevant bits and explore making it more general purpose for API clients.

Thank you very much for the information. I'm going to start the exploration. Hopefully it won't take too long to get something out into the open

**Comment by shiftkey** [comment]
> It may very well have been me :grinning:, as I have been sitting on this for a long time

Nah, it wasn't you - I'm pretty sure it was for the [Confluence API](https://docs.atlassian.com/confluence/REST/latest/) but I think they were speaking more generally in terms of the Octokit architecture

**Comment by M-Zuber** [comment]
¯\_(ツ)_/¯ 
They have nice docs btw :wink:
