### ISSUE TITLE
Port LinqpadSnippetsCompileCorrectly test to F# code

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1081]
Initially we had the ability to test the LINQPad samples would compile from build scripts.

Unfortunately we realised the scripts would download and test against the NuGet package for the latest public release, rather than the local assemblies for the latest source code. So we couldn't test the scripts worked against the latest assemblies. See #987 for an example where we were caught out.

As part of v0.18 - see #1080 - we've now moved this back into an integration test `LinqpadSnippetsCompileCorrectly`, which demonstrates how to rewrite the snippet to reference local assemblies.

I'd love for this test to go back into the build scripts. If someone is interested in porting the C# code to F# so we can do this it'd be greatly appreciated.

See #983 for the previous discussion on this.

**Comment by mderriey** [comment]
I'd like to give it a shot.

Bear with my ignorance, I didn't really understand why that test should be ported to F#. I read through #983 and you mentioned that it could be run inline. Could you shed some light?

Also, would you be able to provide some guidance for the first steps to take to get going? Where should the test be moved to?

Thanks!

**Comment by ryangribble** [comment]
Hi @mderriey 

As far as I can gather, in order to test the LinqPad samples the proposal is that during the build, we rewrite the linqpad files to use local reference to the octokit DLLs (ie those that were just built) instead of pulling nuget packages (which dont contain the very latest changes in the build) then execute them to ensure they dont have any errors.  @shiftkey even ended up writing an example in c#

> I didn't really understand why that test should be ported to F#

The octokit.net build system is currently using FAKE, which I assume means we need that "rewrite linqpad files to contain local references and execute them" code to be in F# as a native task in the build.  

> Where should the test be moved to?

Im guessing it wouldnt be a test anymore but more so a task in [the build script](https://github.com/octokit/octokit.net/blob/b4476f173944c93a9500949a467c4bd91a474639/build.fsx)

**Comment by mderriey** [comment]
Thanks a lot for the explanations, it makes more sense now.

I'll have a look at the build scripts to see if we already have custom build steps or something alike that I can use as a starting point.

Still, if you have more info/guidance, it'll be very appreciated.

Thanks again!
