### ISSUE TITLE
implement IEqualityComparer on request and response models

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1109]
I wanted to write a simple test to compare two sets of results from the Observable-based API:

``` csharp
var startOptions = new ApiOptions
{
    PageSize = 5,
    PageCount = 1
};

var firstPage = await _releaseClient.GetAll(owner, name, startOptions).ToList();

var skipStartOptions = new ApiOptions
{
    PageSize = 5,
    PageCount = 1,
    StartPage = 1 // this is the bug, should be 2
};

var secondPage = await _releaseClient.GetAll(owner, name, skipStartOptions).ToList();

Assert.NotEqual(firstPage, secondPage);
```

However, as these models did not implement `IEqualityComparer` they were always returning true, even when I had a bug in the pagination code.

Generally speaking, I think having this in the library is A Good Thing, even if it's a bit of work to apply it to all the models in the codebase.

Also, am I missing any other interfaces here that are useful? `IComparable`?

@ryangribble mentioned doing this for request models as well, and I'd love to hear from him here about where that adds value to his use cases with Octokit.

**Comment by ryangribble** [comment]
Just to clarify, I didnt have a current "real world" use case, it was more I was in the same situation as you... when writing unit/integration tests for octokit.net API implementation, it would have been useful to just check that the passed response object was "equal" to the one I expected, rather than having to check various sub properties of the object

eg 
https://github.com/octokit/octokit.net/pull/1099/files#diff-6efea07273a6a72156d27872523d4c43R37
https://github.com/octokit/octokit.net/pull/1108/files#diff-09c9ae6c3dd1dae7716e5204c9d936feR143

Im sure I could have written those checks better anyways :P

**Comment by Haacked** [comment]
`IEqualityComparer` makes sense to me. `IComparable` is more for sorting items. Doesn't seem like a thing you'd do with response objects.
