### ISSUE TITLE
[META] updating the repository labels

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1137]
It's been a while since I looked at the labels and there's a few changes I'd like to make:

 - `easy-fix` -> `up-for-grabs` - I think this reflects the intent better for where new contributors can get started. We could also introduce a `easy` label to differentiate big tasks from not-so-big tasks
 - `fix` - I want to label PRs with this label to indicate where a PR addresses a bug
 - `feature` - this label should be applied to PRs which implement a new feature
 - `miscellaneous` - PRs that are not related to features or bugfixes

I call out these three tags because I want to simplify release note generation - and using these labels means I can apply them at the time and group these contributions in the release notes - without worrying about having to revisit PRs weeks/months later to remember what was happening.

Thoughts?

**Comment by ryangribble** [comment]
:+1:

Another suggestion that can make the release notes generation more automatable is that you can add a comment to an issue or PR that will define what the release note item should say.

For example, an Issue might say "Error is thrown when XYZ happens" but you want the release notes to say something else, so you make a comment

> release_notes: XYZ could throw an error in some cases, this is now fixed!

The release notes generation process now just needs to see if a PR or issue has this "release_notes" comment on it and use that instead of the title.  Could even fail if an item doesnt have it.  You can also "lock it down" so that only certain user's comments will be seen as valid ```release_notes``` text and so on.

This can then be maintained as we groom/merge PRs and close issues etc, so the actual process of creating release notes doesnt involve any rewording or massaging and can eventually be fully automated

**Comment by shiftkey** [comment]
@ryangribble this sounds like a grand idea! I've got the code lying around which I used to create the starting point for this release, but let's try out including the summary for the next release.

**Comment by Haacked** [comment]
:+1: to all of this.

**Comment by ryangribble** [comment]
> @ryangribble did you want to open an issue for the release notes stuff so we can hash out how that might work separate to this?

Yep Ill do it (over the weekend) :grinning:

**Comment by shiftkey** [comment]
@ryangribble all good, I've plenty to keep me busy anyway :wink:

**Comment by M-Zuber** [comment]
Added a reaction (kudos BTW - awesome work!!).

I really like @ryangribble's proposal. Wonder if we want to incorporate some other tools though - ala https://github.com/GitTools/GitReleaseNotes

**Comment by shiftkey** [comment]
@M-Zuber I'm leaning towards something simple because of two reasons:

1) I built the basic flow out as Octokit API calls in about 5mins
2) This feels like a nice use case for Octokit

**Comment by shiftkey** [comment]
I also removed `enhancement` (any issues tagged with this are now tagged with `feature`) and removed `api-cleanup` - there was one issue and that's now tagged as `up-for-grabs`

**Comment by shiftkey** [comment]
A bit more cleanup - `post-v1` has been removed (I'll bring in a `v1` tag as we get close to API completion) and I've added `meta` to indicate open discussions rather than issues.

**Comment by shiftkey** [comment]
Alright, time to end this labelling spree...
