### ISSUE TITLE
[META] Discussion on coding style

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1244]
Following on from a [recent PR](https://github.com/octokit/octokit.net/pull/1211#issuecomment-205509458) where coding styles came up, I've started this discussion point to see whether we want to have a more official stance on coding style for the repo.

For obvious reasons consistency is important in an open source project (and octokit is already very high in overall consistency stakes I feel), so I don't actually care what specific style is used on any given project, as long as
- there IS some sort of presiding style being used and consistency across the codebase
- it is documented/mentioned somewhere (eg CONTRIBUTING.md)

My personal position on this these days is similar to the conclusion @Haacked came to in [his blog post](http://haacked.com/archive/2015/12/16/to-string-or-not/) which basically amounts to "spending energy in maintaining/documenting a custom coding style, then justifying why things are X instead of Y etc is non trivial... so sometimes adopting something that is a widespread maintanied/external "standard" and pointing towards that (despite not 100% aligning with my personal preferences) can be a good course of action".  

Using an existing one, also makes it more likely that things like community contributions in the form of code formatters/analyzers/convention tests/resharper or VS settings etc, are able to be drawn upon to help achieve that style

@Haacked mentioned the [CoreFx coding style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) and although I disagree personally with a few of their points (specifically I prefer to use `this.` to make it obvious you're dealing with a class member, and although i like `_foo` for class variables, i dont like the idea of `s_foo` and `t_foo` for static and thread variables!) I still would be happy if we simply adopted that standard or something similar.  Alternatively if we want to write up our own style similar to that page, it would be interesting to see how different personal opinions can be among even a small group of people, hah :grinning:

Another option of course, is to continue as we are going, with no "official" style but general good practices and a little flexibility (and sometimes friction) when going through the PR reviews

**Comment by shiftkey** [comment]
So I like the CoreFx coding style with a few extra changes. Let me elaborate:

 - We use `_camelCase` for internal and private fields and use readonly where possible

This is helpful to understand context quickly when dealing with large, complex classes with lots of internal fields and variables. But I don't feel Octokit is at that stage (nor should it be aiming for that). We have lots of small classes composed together, and for the most part the fields we use can be made `readonly` which is the big headache with mixing fields and local variables (accidentally setting a field instead of a variable).

So I'd simplify this to **"We use `camelCase` for internal and private fields and use readonly where possible"**

 - We always specify the visibility, even if it's the default

Again, this is a noise versus value thing for me. I like removing `private` wherever it comes up as that's the default visibility.

I'd change this to **Specify the visibility unless it is private, in which case it should be removed**

**Comment by ryangribble** [comment]
So do you think it's feasible to essentially have our own copy of that md file, with our preferred tweaks, then reinforce it with convention tests? Eg it should be easy enough to have tests that make sure `private` visibility is not specified and variable names never contain underscores

**Comment by shiftkey** [comment]
@ryangribble so I'm pretty sure I can adapt the `.vssettings` file from corefx to address those two. And I guess the R# rules file. I think those alongside with adding this to CONTRIBUTING.md (or something similar) should be good enough.

I'll let others chime in here before I do anything about it.
