### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by MikhailTymchukDX** [octokit/octokit.net#1271]
I try to run the [first sample](https://github.com/octokit/octokit.net/blob/master/samples/linqpad-samples/1-introducing-octokit.linq):
```csharp
using Octokit;
using System;
using System.Threading.Tasks;

namespace GitHubApi {
    class Program {
        static void Main(string[] args) {
            Task task = Do();
            task.Wait();
            Console.ReadKey();
        }

        async static Task Do() {
            var owner = string.Empty;
            var reponame = string.Empty;

            owner = "octokit";
            reponame = "octokit.net";

            var client = new GitHubClient(new Octokit.ProductHeaderValue("octokit.samples"));

            var repository = await client.Repository.Get(owner, reponame);

            Console.WriteLine(String.Format("Octokit.net can be found at {0}\n", repository.HtmlUrl));

            Console.WriteLine("It currently has {0} watchers and {1} forks\n",
                repository.StargazersCount,
                repository.ForksCount);

            Console.WriteLine("It has {0} open issues\n", repository.OpenIssuesCount);

            Console.WriteLine("And GitHub thinks it is a {0} project", repository.Language);

        }
    }
}
```

However, I get an error "The request was aborted: Could not create SSL/TLS secure channel.".
![octocat](https://cloud.githubusercontent.com/assets/17080984/14530395/8682b834-0261-11e6-863a-58a8256dbc83.png)

Accessing GitHub API via browser works OK.

I'm running Windows 8.1 with all latest updates installed, including [KB3109853](https://technet.microsoft.com/en-us/library/security/3109853.aspx).
Application is running .NET 4.6.1 (attached)
[GitHubApi.zip](https://github.com/octokit/octokit.net/files/219239/GitHubApi.zip)

How can I resolve this error?

**Comment by shiftkey** [comment]
The error message itself suggests something is interfering with the TLS handshaking that your computer and `api.github.com`. This often occurs when the client isn't able to validate the certificate it gets from the server. If you have a look at the stack trace for that error it'll likely be deep inside the bowels of `System.Net.Http` stack - way beyond anything that Octokit can control.

My gut feeling is that this is still certificate related - browsers will often look at their own certificate store (sup Firefox) rather than defer to what is installed with the OS (which is what .NET does).

🌵 🌵 🌵 **WARNING: DANGER ZONE** 🌵 🌵 🌵 

What I'd like you to do is tweak the main part of the program to do this:

```
using Octokit;
using System;
using System.Threading.Tasks;
// add these usings
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

... 

static void Main(string[] args)
{
    // add this event handler
    ServicePointManager.ServerCertificateValidationCallback += new RemoteCertificateValidationCallback(AlwaysGoodCertificate);

    Task task = Do();
    task.Wait();
    Console.ReadKey();
}

// add this callback
static bool AlwaysGoodCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors policyErrors)
{
    // add a breakpoint here, this will tell you what the error is
    var errors = policyErrors;

    return true;
}
```

You can then view at the certificates that were received as part of the handshaking and see what the error is that you're receiving. But do not keep this code around once you find the problem - you should fix it and then cleanup this code, as bypassing SSL/TLS handshaking is crazy dangerous in general.

**Comment by MikhailTymchukDX** [comment]
Well, I did this, but breakpoint can not be hit - I get an exception before this line is executed.

**Comment by devkhan** [comment]
Just a wild guess, but can you try opening `api.github.com` in VS's internal browser?

It may be informative if it is a certificate related problem, AFAIK.

**Comment by shiftkey** [comment]
> I get an exception before this line is executed.

It's hard to say without more information what's happening here. 

> Accessing GitHub API via browser works OK.

Which browser?

**Comment by MikhailTymchukDX** [comment]
@devkhan I can not reach [this url](https://api.github.com/repos/DevExpress/AjaxControlToolkit/issues?state=closed&filter=all) from inside VS:
![image](https://cloud.githubusercontent.com/assets/17080984/14580301/f5af11b4-03d1-11e6-98a5-a5d90b0a391c.png)

@shiftkey I tried IE 11 and Chrome, both OK.
However, Firefox gives me this:
![image](https://cloud.githubusercontent.com/assets/17080984/14580306/226060c8-03d2-11e6-9acd-98a220737dc6.png)

**Comment by MikhailTymchukDX** [comment]
Thanks everyone for helping, I found the cause of the problem.
It was ESET Antivirus bug, that blocks all HTTPS requests until explicitly allowed.
Chrome an IE were in exclusion lists, so they work OK.
