### ISSUE TITLE
Issue.PullRequest is not fully populated when calling IGitHubClient.Search.SearchIssues?

### ISSUE THREAD

**Issue by mssealsbuzz** [octokit/octokit.net#1403]
When calling IGitHubClient.Search.SearchIssues, Issue.PullRequest is not fully populated in SearchIssuesResult.Items. Some examples include PullRequest.Merged and PullRequest.MergedBy. I can call IGitHubClient.PullRequest.Get to retrieve pull request's details separately. But is there an option to return pull request's details when calling IGitHubClient.Search.SearchIssues?

Here is my pseudo code.

```
SearchIssuesRequest request = new SearchIssuesRequest
{
    Repos = repositoryCollection,
    Updated = new DateRange(startTime, endTime),
    Labels = labels,
    SortField = IssueSearchSort.Updated,
    Page = pageIndex,
    PerPage = issueCountPerPage,
};
SearchIssuesResult result = await this._client.Search.SearchIssues(request);
```

**Comment by ryangribble** [comment]
Yeah I ran into this myself yesterday.  Unfortunately looking at the [API docs example](https://developer.github.com/v3/search/#example-2) shows that the GitHub API really only returns a couple of Url's (Html, Diff, Patch) for the Pull Request, and not the entire object which would indeed be handy.

In my case I ended up using the Search Issue API to get a list of PRs for a specific repo that were merged in a specific date range, THEN i fired off concurrent async calls to load those subset of PR's individually.  This still turned out to be much faster than loading all PRs for the repo with the single `PullRequest.GetAllForRepository()` call (as under the covers, that pages through multiple results).  Also the GetAll call will get slower as the repository grows, whereas the search + parallel PR load is a bit more constrained since the commit (date) ranges in our case at least are for up to only a handful of 2 week iterations rather than the entire repository

**Comment by shiftkey** [comment]
Seconding what @ryangribble said - this is a limitation of the server-side, and unfortunately due to us sharing models this is giving consumers false hope that it should be available...

**Comment by ryangribble** [comment]
> sharing models

Do you think we should have some cut down models ma,ed something like `PullRequestStub` or `IssuePullRequestInfo` for these cases?

**Comment by shiftkey** [comment]
@ryangribble that's what i'm leaning towards, but I need to think more on how we can make this maintainable because it could be a lot of work to migrate and keep in sync...

**Comment by Eilon** [comment]
Yeah I kept wondering why things like Comment count were always 0 for PRs. Kind of frustrating that I have to make additional calls for each PR I'm interested in... kind of blows away the rate limit with the amount of data I'm crunching!
