### ISSUE TITLE
Null Fields on commits returned when using Compare API

### ISSUE THREAD

**Issue by gep13** [octokit/octokit.net#1433]
I am using the following snippet as a proof of concept for extracting the list of contributors to a milestone:

```
            var githubClient = CreateGitHubClient();
            var compareResults = githubClient.Repository.Commit.Compare("cake-build", "cake", "v0.14.0", "v0.15.0").Result;

            var authors = new List<string>();

            foreach (var commit in compareResults.Commits)
            {
                var author = commit.Author?.Login;

                if (!authors.Contains(author))
                {
                    authors.Add(author);
                }
            }

            using (var writer = new StreamWriter("c:\\temp\\authors.txt"))
            {
                foreach (var author in authors)
                {
                    writer.WriteLine("- [{0}](https://github.com/{0})", author);
                }
            }
```

However, I am finding that the Author field is sometimes returning as a null object:

![image](https://cloud.githubusercontent.com/assets/1271146/17171469/ba48b6a4-53e8-11e6-8d7c-659e3407677b.png)

The commit in question is this one:

https://github.com/cake-build/cake/commit/0ddbae23114a3d33f44f9058cebfa7e817082855

Any ideas on what is going on here?

Thanks!

**Comment by ryangribble** [comment]
G'day @gep13 

It looks to be related to those specific users.  In the 108 commits in your comparison, there are 5 commits with `Author == null` and `Committer == null` and all 5 of them are from 2 unique contributors.  Also there are no other commits from these contributors in this comparison range that DO provide Author/Committer details.  In other words, ALL commits from these 2 authors present with this problem.

I've confirmed that the actual json response has this field as `null` (ie there is nothing happening inside octokit, this is coming from the github api itself)

``` json
{
      "sha": "e61ec08215107576c2dea8cb080db9d61f1f1780",
      "commit": {
        "author": {
          "name": "Scott Mackay",
          "email": "scott.mackay@maclean.co.uk",
          "date": "2016-06-02T16:43:17Z"
        },
        "committer": {
          "name": "Gary Ewan Park",
          "email": "gep13@gep13.co.uk",
          "date": "2016-07-14T20:30:49Z"
        },
        "message": "(GH-960) Add configuration for default NuGet source",
        "tree": {
          "sha": "cdde0902a97c65bd1444c658cf9593eb8935c661",
          "url": "https://api.github.com/repos/cake-build/cake/git/trees/cdde0902a97c65bd1444c658cf9593eb8935c661"
        },
        "url": "https://api.github.com/repos/cake-build/cake/git/commits/e61ec08215107576c2dea8cb080db9d61f1f1780",
        "comment_count": 0
      },
      "url": "https://api.github.com/repos/cake-build/cake/commits/e61ec08215107576c2dea8cb080db9d61f1f1780",
      "html_url": "https://github.com/cake-build/cake/commit/e61ec08215107576c2dea8cb080db9d61f1f1780",
      "comments_url": "https://api.github.com/repos/cake-build/cake/commits/e61ec08215107576c2dea8cb080db9d61f1f1780/comments",
      "author": null,
      "committer": {
        "login": "gep13",
        "id": 1271146,
        "avatar_url": "https://avatars.githubusercontent.com/u/1271146?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gep13",
        "html_url": "https://github.com/gep13",
        "followers_url": "https://api.github.com/users/gep13/followers",
        "following_url": "https://api.github.com/users/gep13/following{/other_user}",
        "gists_url": "https://api.github.com/users/gep13/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gep13/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gep13/subscriptions",
        "organizations_url": "https://api.github.com/users/gep13/orgs",
        "repos_url": "https://api.github.com/users/gep13/repos",
        "events_url": "https://api.github.com/users/gep13/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gep13/received_events",
        "type": "User",
        "site_admin": false
      },
      "parents": [
        {
          "sha": "a3a26d74be0cac4ea820ce74bc4a96ce7dfd6358",
          "url": "https://api.github.com/repos/cake-build/cake/commits/a3a26d74be0cac4ea820ce74bc4a96ce7dfd6358",
          "html_url": "https://github.com/cake-build/cake/commit/a3a26d74be0cac4ea820ce74bc4a96ce7dfd6358"
        }
      ]
    },
```

You can also see this fact if you look at the commits themselves:
https://github.com/cake-build/cake/commit/e61ec08215107576c2dea8cb080db9d61f1f1780, https://github.com/cake-build/cake/commit/0ddbae23114a3d33f44f9058cebfa7e817082855, https://github.com/cake-build/cake/commit/545ce71f3cf6b9ac25fb2249a47e6f811b63a31f, https://github.com/cake-build/cake/commit/5faa048cf153527cadd510a68a48a3d50b6e1974, https://github.com/cake-build/cake/commit/3f948dbe1297f1cf025cf87a7ee5c6f9f721338f

The author is NOT a normal hyperlink to a github user profile, instead it is just the "display name" of the author, according to the git commit data:
![image](https://cloud.githubusercontent.com/assets/5425163/17176917/392979ae-5452-11e6-8366-29b7eb0de62b.png)

Same in the [commit list](https://github.com/cake-build/cake/commits/develop?page=3) of the repo, we only see the git author name and not the github author's hyperlinked profile
![image](https://cloud.githubusercontent.com/assets/5425163/17176953/59fef028-5452-11e6-9cfa-b3846de36258.png)

In terms of the GitHub API object model, the items returned in the comparison results are what we call `GithubCommits` that have "github" info on them - things like organization/owner, and full "user" objects for Author and Commiter (in these cases this info is null).  Then there is also a `Commit` object that is more the pure "git" info, which include author/commiter details from an underlying git point of view (so you get the author's Name and Email, but not any github specific info like login)... just like any git client would show.  
![image](https://cloud.githubusercontent.com/assets/5425163/17177176/7bfca368-5453-11e6-803a-bb173b8aa68c.png)

So if your intention is to generate a list of people who contributed commits, potentially you could go with `commit.Commit.Author.Name` rather than the github login, or possibly the github author.login is null, fallback to using the git author name instead.

Now you've raised this here I realise I actually ran into this just the other day on our GitHub Enterprise instance where when I retrieved commits from a pull request not all `Author` fields were populated.  I didn't dig into it too much and just ended up using `Commit.Author.Name` instead... but I think it's likely to be the same thing.

Maybe privacy settings on those users or email verification status?  I might ping github support about this to see if there is an explanation

**Comment by ryangribble** [comment]
PS I listened to your DNR podcast on cake recently and although I knew it was out there it's motivated me to put it on the todo list to go and check it out!  :+1:

I havent looked as yet, but I was thinking it'd be cool to have some "github" tasks in cake (using octokit.net of course!) if you don't already...

**Comment by gep13** [comment]
Thank you so much for digging into this!

>@ryangribble said...
I might ping github support about this to see if there is an explanation

If you could I would really appreciate it.

The idea was really to create the list that you can see here:

http://cakebuild.net/blog/2016/07/cake-v0-15-0-released

![image](https://cloud.githubusercontent.com/assets/1271146/17177674/723693aa-540a-11e6-8bb7-421df37a8760.png)

Which is a link to that person's GitHub profile page.  I can certainly fall back to using the Display Name for that user in the case where the Login name isn't provided.

@adamhathcock @markrendle @wwwlicious you were the three users that were not included in the list that I generated using Octokit for our blog post.  Are you aware of any issues with your account regarding email verification status, that would stop this being shown.  Or any security restrictions that you have put on our account to stop this information coming through?  Thanks!

**Comment by gep13** [comment]
>@ryangribble said...
PS I listened to your DNR podcast on cake recently and although I knew it was out there it's motivated me to put it on the todo list to go and check it out!  :+1:
I havent looked as yet, but I was thinking it'd be cool to have some "github" tasks in cake (using octokit.net of course!) if you don't already...

Woot!  Glad to hear that it helped motivate you to look into it! :smile: 

We have an Addin for doing some command line Git things.  You can find this [here](https://github.com/WCOMAB/Cake_Git), but nothing directly against the GitHub API.  Although, we do have support for [GitReleaseManager](https://github.com/GitTools/GitReleaseManager) which uses Octokit under the hood to allow the generation of a GitHub release with release notes based on Issues/PR's in a milestone, uploading assets into a release, publishing a release, and then closing a milestone, etc,

The reason that this question came up was that I was planning on adding support for generating a list of contributors in a release to GitReleaseManager, which I thought would be a useful addition.

Would love to hear if you have any other thoughts in this area, or if you wanted to create a Cake.GitHub addin.

**Comment by wwwlicious** [comment]
@gep13 There is nothing I'm aware of, I do commit using a few email addresses across a few machines and apps so things aren't always consistent, but my main account email is private and have two-factor auth enabled if that makes any difference?

Guess I'm just a :snowflake: lol

**Comment by ryangribble** [comment]
>  I do commit using a few email addresses 

Are all the email addresses linked to your github profile?

**Comment by wwwlicious** [comment]
No they aren't

**Comment by ryangribble** [comment]
Assuming the email address on the commits being discussed here is one that isn't, that would explain it 

Ideally you should add all your email addresses you use in git, under your github profile so you get stats for commits made via that email

**Comment by markrendle** [comment]
If it helps, my commit and push was done using the GitHub desktop client for Windows, which is the only thing that works with the corporate network I was on.

**Comment by gep13** [comment]
@ryangribble after associating the emails with the account, should I expect to see a non null in the response of the octokit call?

**Comment by markrendle** [comment]
Ah, but email somehow got set to one I didn't have in my Profile, an omission I have now rectified; alas, too late to make it into Gary's blog post.

**Comment by gep13** [comment]
@markrendle I retrospectively added you too the blog post :smile:

**Comment by ryangribble** [comment]
> @ryangribble after associating the emails with the account, should I expect to see a non null in the response of the octokit call?

yep!  Once the email address is "claimed" the output will contain the expected github `Author`.  

As there's nothing to stop this happening on any future commit/author, it's probably a good idea to implement the fallback to `commit.Commit.Author.Name` when `commit.Author` is `null`

**Comment by gep13** [comment]
>@ryangribble said...
yep! Once the email address is "claimed" the output will contain the expected github Author.

Perfect!  I have just confirmed that this is now the case.  I now get the `Author` property populated for both @markrendle and @wwwlicious.  The only one that is still not populated is @adamhathcock but I am going to assume that this is the same issue.

>@ryangribble said...
As there's nothing to stop this happening on any future commit/author, it's probably a good idea to implement the fallback to commit.Commit?.Author?.Name when commit.Author?.Login is null

Agreed, I will go that.

I am going to go ahead and close this, thanks for all your help!

**Comment by adamhathcock** [comment]
I'm sure my email is the same issue because I did fixes at work with git instead of home.  I'll fix my profile.  Thanks!

**Comment by gep13** [comment]
>@adamhathcock said...
I'm sure my email is the same issue because I did fixes at work with git instead of home. I'll fix my profile. Thanks!

Perfect, thank you! :smile:
