### ISSUE TITLE
Can't search C# code

### ISSUE THREAD

**Issue by aetos382** [octokit/octokit.net#1459]
When I specify Language.CSharp to [SearchCodeRequest.Language] (https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/SearchCodeRequest.cs#L90), [SearchCode] (https://github.com/octokit/octokit.net/blob/master/docs/search.md#search-code) request is failed.
Because '#' character contains in request URL and subsequent part is not passed to the server.

The request URL contains the results of [Language.ToParameter] (https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/SearchCodeRequest.cs#L164) method.
And the value of ParameterAttribute of Language.CSharp is ["C#"] (https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/SearchRepositoriesRequest.cs#L449-L450).

I think should not use Language.ToParameter method in SearchCodeRequest.MergedQualifiers, because it is not used in [SearchRepositoriesRequest] (https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/SearchRepositoriesRequest.cs#L146).

**Comment by shiftkey** [comment]
Can you provide a failing test here, so we can verify the issue?

**Comment by aetos382** [comment]
Please test this.

```csharp
var client = new GitHubClient(new ProductHeaderValue("SearchCodeSample"));

var searchCodeRequest = new SearchCodeRequest
{
    Language = Language.CSharp
};

searchCodeRequest.Repos.Add("octokit/octokit.net");

// generated URL: "https://api.github.com/search/code?page=1&per_page=100&order=desc&q=language:C#+repo:octokit/octokit.net"
// expected URL : "https://api.github.com/search/code?page=1&per_page=100&order=desc&q=language:CSharp+repo:octokit/octokit.net"
var result = client.Search.SearchCode(searchCodeRequest).Result;
```

Please find the [entire code](https://github.com/aetos382/SearchCodeSample).

**Comment by dampir** [comment]
@aetos382 good catch! The fix of this issue looks very simple and if you need this fix as ASAP just change attribute value on Language enum.

So, this one [SearchRepositoriesRequest.cs#L449](https://github.com/octokit/octokit.net/blob/58833602b7e79cc2fc85802ca97e108298b86353/Octokit/Models/Request/SearchRepositoriesRequest.cs#L449)
``` csharp
 [Parameter(Value = "C#")]
 CSharp,
``` 

should be changed on:
``` csharp
 [Parameter(Value = "CSharp")]
 CSharp,
```

Anyway, I made some investigation why integration tests in Octokit didn't catch this issue. It's quite interesting thing! Octokit have integration test for `SearchCodeRequest` [SearchClientTests.cs#L436](https://github.com/octokit/octokit.net/blob/b47b05489e2b06b3b498b94790c5b822fcfb0414/Octokit.Tests.Integration/Clients/SearchClientTests.cs#L436): 

``` csharp
    [IntegrationTest]
    public async Task SearchForExcludedLanguage()
    {
        var language = Language.CSharp;

        // Search for issues by include filter
        var request = new SearchIssuesRequest("octokit");
        request.Language = language;

        var issues = await _gitHubClient.Search.SearchIssues(request);

        // Ensure we found issues
        Assert.NotEmpty(issues.Items);

        // Search for issues by exclude filter
        var excludeRequest = new SearchIssuesRequest("octokit");
        excludeRequest.Exclusions = new SearchIssuesRequestExclusions
        {
            Language = language
        };

        var otherIssues = await _gitHubClient.Search.SearchIssues(excludeRequest);

        // Ensure we found issues
        Assert.NotEmpty(otherIssues.Items);

        // Ensure no items from the first search are in the results for the second
        Assert.DoesNotContain(issues.Items, x1 => otherIssues.Items.Any(x2 => x2.Id == x1.Id));
    }
```
As you can see to create SearchIssuesRequest class the constructor with one parameter is used:

``` csharp
var request = new SearchIssuesRequest("octokit");
```

The GitHub Search Code Api has some restrictions and [one of them is](https://developer.github.com/v3/search/#search-code):

> You must always include at least one search term when searching source code. For example, searching for language:go is not valid, while amazing language:go is.

So, how this test can be correct in case of this bug with '#' symbol? Answer is simple: this test is correct  but not for C#. Instead of sending search request for C# it is sending request on C language!

``` csharp
    [IntegrationTest]
    public async Task SearchForExcludedLanguage()
    {
        var language = Language.CSharp;

        // Search for issues by include filter
        var request = new SearchIssuesRequest("octokit");
        request.Language = language;

        // generated URL: "https://api.github.com/search/?page=1&per_page=100&order=desc&q=GitHub+language:C"
        // Search issues on C language instead of C#
        var issues = await _gitHubClient.Search.SearchIssues(request);

        // Ensure we found issues
        Assert.NotEmpty(issues.Items);

        // Search for issues by exclude filter
        var excludeRequest = new SearchIssuesRequest("octokit");
        excludeRequest.Exclusions = new SearchIssuesRequestExclusions
        {
            Language = language
        };

        var otherIssues = await _gitHubClient.Search.SearchIssues(excludeRequest);

        // Ensure we found issues
        Assert.NotEmpty(otherIssues.Items);

        // Ensure no items from the first search are in the results for the second
        Assert.DoesNotContain(issues.Items, x1 => otherIssues.Items.Any(x2 => x2.Id == x1.Id));
    }
```

@aetos382  in order to use SearchIssuesRequest in right way you have to use the next constructor:

``` csharp
        /// <summary>
        /// Search using a specify keyword
        /// </summary>
        /// <param name="term">The term to filter on</param>
        public SearchIssuesRequest(string term) : base(term)
        {
            Repos = new RepositoryCollection();
        }
```

and do not use SearchIssuesRequest parameterless constructor that created for correct Json serialization.

I'm going to create PR to fix this bug.
