### ISSUE TITLE
No "Watchers" available in Octokit.net?

### ISSUE THREAD

**Issue by tang-jason** [octokit/octokit.net#1470]
Using
`client.Search.SearchRepo(new SearchRepositoriesRequest(searchTerm));`

I don't seem to find "watchers" listed from the repos that I pulled. Is this available/implemented in Octokit?

**Comment by ryangribble** [comment]
Assuming I am understanding what you're referring to, I believe the API field name (and hence the octokit member name) is `StargazersCount`

**Comment by tang-jason** [comment]
@ryangribble  Isn't the StargazersCount referring to "Star". Take octokit for example, it has 

> Watch: 123 
> Star: 1052 
> Fork: 531

"Watch" is the one I am looking for.

**Comment by ryangribble** [comment]
Ah sorry, indeed you are correct 

There is a `watchers_count` field in the API response that is not currently implemented in octokit.net. It should be a simple change, just adding a member called `WatchersCount` to the `Repository` object 

Typically missing fields like this are added as people run into them, but I would actually like to proactively add useful missing fields. I started rhetoric first step by auditing API response fields that are missing from our response model classes in #1400 (and sure enough, these watcher fields are listed)

**Comment by ryangribble** [comment]
Hey so I actually stumbled upon an old issue #699 that explains this `WatchersCount` property was actually deprecated and `SubscribersCount` is the field you want to use for this...  But then `SubscribersCount` field was also deprecated/removed in issue #736.  So apparently the "correct" way to retrieve this info is using the "Watchers" API `WatchedClient.GetAllWatchers()` instead.

Although, since the API responses still include these fields and the linked blog in #699 mentions they will be supported indefinitely in API v3, I'm not sure if it would be OK to add them back in again or not.  @shiftkey or @Haacked care to comment on these historic issues?

**Comment by shiftkey** [comment]
Assigning to myself to remember and investigate
