### ISSUE TITLE
Event types not covered by EventInfo API appearing in event stream, causing argument exception

### ISSUE THREAD

**Issue by andrejo-msft** [octokit/octokit.net#1502]
https://api.github.com/repos/Microsoft/WinObjC/issues/1305/events

In this set of events, notice a **review_dismissed** event. review_dismissed does not appear as an enum in the EventInfo.cs list, so a call of:

                IReadOnlyList<EventInfo> issueEvents = await Client.Issue.Events.GetAllForIssue("Microsoft", "WinObjC", 1305);

results in an **ArgumentException: Requested value 'reviewdismissed' was not found.** error.

I also notice in another set of events we are tracking that 'base_refchanged' is also causing such an error.

How is the enum for EventInfo getting added to? I notice that these events are also not shown as supported event types in the docs. (https://developer.github.com/v3/issues/events/)

**Comment by ryangribble** [comment]
Evidently th new reviews stuff has added some new event types to this API (and probably to webhooks as well) 

I think it's hard to track this sort of thing with a concrete enum as we don't want to break everytime an upstream event type gets added. Yet making it a string loses some niceties as well. 

I'd propose we could shoot for a best of both worlds approach involving 
- have an `Unknown` enum member and catch any failed deserialization so this value can be used rather than failing
- add a `BlahText` property to always provide what the actual returned value was  

Thoughts?

**Comment by andrejo-msft** [comment]
I like that rather a lot. Otherwise, we’ll continue to hit one-off issues such as these every time a new set of features around issue events are released.

-Drew

**Comment by ryangribble** [comment]
Any thoughts from @shiftkey @maddin2016 @M-Zuber about this enum approach?

**Comment by M-Zuber** [comment]
That approach makes the most sense.

Would be cool if the serializer could phone home on error and open an issue to add the new value to the enum.

**Comment by maddin2016** [comment]
👍 to @M-Zuber

**Comment by maddin2016** [comment]
But what if there n new members at the same time.

**Comment by nickfloyd** [comment]
Resolved with: #1536 and #1591
