### ISSUE TITLE
What is the integer in PullRequest.Get? .NET

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1508]
I have a question. What is the integer that appears as the 2nd parameter of the Commit,Files and Get methods?
 I suppose that the integer is how many pull req i want to get. But i want to get all pull request.

```
await github.Repository.PullRequest.Commits(repoID,integer)
await github.Repository.PullRequest.Get(repoID,integer)
await github.Repository.PullRequest.Files(repoID,integer)
```

Moreover, if doesn't exist a pull request in a repo, octokit throws me an exception..
Some help?

**Comment by shiftkey** [comment]
The second parameter is the unique identifier for a pull request. For example, #1503 is the identifier for this pull request: https://github.com/octokit/octokit.net/pull/1503

If you just want to enumerate all open pull requests, use this method:

```
var pullRequests = await client.PullRequest.GetAllForRepository("octokit", "octokit.net");
var first = pullRequests[0];
var number = first.Number;
```

> Moreover, if doesn't exist a pull request in a repo, octokit throws me an exception..

This is due to a 404 being returned from the GitHub API - we just surface that because we don't have any data to give the caller.

**Comment by l1salvatore** [comment]
Sorry, but how access to commits and files of pullrequest? I only access with commits and files
