### ISSUE TITLE
Release repositoy missing in GitHubClient

### ISSUE THREAD

**Issue by zeppaman** [octokit/octokit.net#1565]
According with http://octokitnet.readthedocs.io/en/latest/releases/ Release repositoy should be a member of  GitHubClient, but seems to be missing.
https://github.com/octokit/octokit.net/blob/master/Octokit/GitHubClient.cs

I'm using version 0.24 from nuget. May I add some other libraries or add some namespace to see memebrer by extension classes?

**Comment by ryangribble** [comment]
Hi @zeppaman  thanks for reaching out. 

The good news is, the Releases client is implemented, you will find it at `client.Repository.Release` rather than `client.Release`

The bad news is that the documentation is out of date! If you would consider sending a pull request to correct [the offending doc file](https://github.com/octokit/octokit.net/blob/master/docs/releases.md) that would be wonderful! 

Otherwise we can raise an issue for somebody to fix it up 👍
