### ISSUE TITLE
Calling RepoCollaboratorsClient.Add with CollaboratorRequest param swallows exceptions

### ISSUE THREAD

**Issue by joensindholt** [octokit/octokit.net#1575]
If I call the `RepoCollaboratorsClient.Add(string owner, string name, string user)` without specifying credentials I get an "Octokit.AuthorizationException: Bad credentials". That's expected.

If I call the `RepoCollaboratorsClient.Add(string owner, string name, string user, CollaboratorRequest permission)` overload the same exception is swallowed and instead a false boolean is returned, making it impossible to know why the operation is failing.

I would expect both methods to behave in the same way, preferably throwing exceptions.

Is there a reason for the difference, that I'm just not seeing?

**Comment by shiftkey** [comment]
@joensindholt the reason is they're two different code paths (and that we don't look at the exception for the second one):

 - https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/RepoCollaboratorsClient.cs#L151-L158

 - https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/RepoCollaboratorsClient.cs#L171-L186

I gather surfacing the `AuthorizationException` is probably the better thing to do here - if you're keen to contribute a fix I can guide you through the process.

**Comment by joensindholt** [comment]
I would very much like to look at doing a fix. I see you have a "How to Contribute", but if you have further information I'd like it - this being my first time ;)

**Comment by shiftkey** [comment]
If you've got VS2015 installed, you should be able to just open the solution and build it locally.

There's a bunch of additional things in our [CONTRIBUTING.md](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) docs - running tests, etc - and this [overview](https://github.com/octokit/octokit.net/blob/master/OVERVIEW.md) of the code is probably helpful.

**Comment by joensindholt** [comment]
I'll give it a shot - thanks
