### ISSUE TITLE
Can i use Octokit.net in Unity3D?

### ISSUE THREAD

**Issue by EmpireWorld** [octokit/octokit.net#1603]
Hi.

Can i use Octokit.net in Unity3D?

It seems Octokit.net does not supports unity 3d mono2x.

Thanks.

**Comment by shiftkey** [comment]
I'm honestly not sure which version of the .NET Framework is supported by Unity 3D.

If it is earlier than 4.0, we don't have plans to support it due to the heavy usage of the Task Parallel Library. And we dropped 4.0 support a while ago because there were significant gains to using .NET 4.5.

A supported version of .NET Standard is almost ready - I think the target is .NET Standard 1.1 - but that may not be a solution here.

**Comment by EmpireWorld** [comment]
So what should i do?

Do i use GitHub HTTP API?

**Comment by shiftkey** [comment]
@EmpireWorld that's what I'd recommend - use the endpoint and snippet examples from https://developer.github.com/v3/ and have a bit of JSON parsing of the response to get the data you need in C# objects.

You could extract the relevant source file for the response models from our [Octokit/Models/Response folder](https://github.com/octokit/octokit.net/tree/master/Octokit/Models/Response) and add them into your project to save time with models and parsing, but I'd recommend getting familiar with the API first.
