### ISSUE TITLE
Debugging Octokit source does not work

### ISSUE THREAD

**Issue by jamesqo** [octokit/octokit.net#1614]
Hi, I just followed [the instructions here](https://github.com/octokit/octokit.net/blob/master/docs/debugging-source.md) to debug an issue I was having with Octokit. However, checking **Enable source server support** in VS and pressing F11 on an Octokit method does not take me into the method. Is debugging like this still supported?

**Comment by ryangribble** [comment]
What version of the library are you using?

**Comment by jamesqo** [comment]
@ryangribble `0.24.1-alpha0001`.

**Comment by ryangribble** [comment]
Ah yep that was our alpha dotnetcore build and won't support source
debugging because at the time SourceLink tooling didn't exist for
dotnetcore.

Previous releases it should work...

And the good news that it's already now re/implemented in our dotnetcore
work, so will be there in the next release (occuring soon, as few as a
couple of things get sorted out).

You can grab the  current master build off our appveyor feed if you want to
try it out now

On 10 Jun 2017 22:47, "James Ko" <notifications@github.com> wrote:

@ryangribble <https://github.com/ryangribble> 0.24.1-alpha0001.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/octokit/octokit.net/issues/1614#issuecomment-307563124>,
or mute the thread

**Comment by jamesqo** [comment]
@ryangribble I am trying with a .NET Framework app, but it's not working there either.

![sourcelink_wont_work](https://user-images.githubusercontent.com/9159214/27003213-77aefd1c-4dc0-11e7-8b03-84abbf5fce98.gif)

Proof that I've enabled the source server setting:

<img width="527" alt="sourcelink_config_correct" src="https://user-images.githubusercontent.com/9159214/27003224-c8f311ae-4dc0-11e7-8380-765232b06374.PNG">

**Comment by ryangribble** [comment]
Using 0.23 or the master branch build from appveyor?

**Comment by jamesqo** [comment]
This is using [0.24](https://www.nuget.org/packages/Octokit/0.24.0) (the one that doesn't support .NET Core).

**Comment by jamesqo** [comment]
@ryangribble I just tried again, using the latest AppVeyor build with a .NET Core app, and it doesn't work there either. Not sure what I could be doing wrong on my end 🙁

**Comment by ryangribble** [comment]
For the dotnetcore version on appveyor, you need to be in vs2017 and using the "new" sourcelink option 

Details here : https://github.com/ctaggart/SourceLink

**Comment by jamesqo** [comment]
@ryangribble I already had both SourceLink v1 and v2 enabled and was using VS2017. I ended up git cloning the repo and inserting a new test to diagnose the issue. Regardless, thanks very much for your help :smile:

I'm closing this issue for now, but if anyone else has had problems with debugging too, comment and I'll reopen.
