### ISSUE TITLE
Support for .NET Standard broke .NET 4.5

### ISSUE THREAD

**Issue by davidkwoods** [octokit/octokit.net#1634]
While updating to the new csproj format, it looks like some DefineConstants were dropped from .NET 4.5 builds.  One of these, SIMPLE_JSON_READONLY_COLLECTIONS, broke deserialization of nested arrays in at least some cases.  The CompareResult object, for example, defines its Commits and Files properties as IReadOnlyList<T>, but on .NET 4.5 this Type is excluded from the set of Types considered lists in SimpleJson.cs, preventing their deserialization.

The simple fix is to add SIMPLE_JSON_READONLY_COLLECTIONS to the net45 DefineConstants in Octokit.csproj, and it appears to work well, but it merits further investigation to make sure that this wasn't the only case where the preprocessor directives have introduced issues.

**Comment by ryangribble** [comment]
Thanks for advising, can you confirm which nuget package version you're using? 

Also if you could add a failing test via a PR that would be awesome and help confirm a fix 

CC @mderriey

**Comment by mderriey** [comment]
I tracked this back to https://github.com/octokit/octokit.net/commit/ac49d2ad09fd41677aec32c3b842d64488770124 where conditional compilation symbols were apparently not brought over correctly from `.xproj` to `.csproj`.

It should be an easy fix, but I think it's also a great opportunity to maybe have a look at running tests against both targets, `net45` and `netstandard1.1`.

I'm happy to have a stab at this one.
@ryangribble since it would be, in my opinion, too heavy to run integration tests against both targets, what would be the best way to reproduce this in a failing test? take a JSON response and try to deserialise it?

**Comment by ryangribble** [comment]
Thanks @mderriey for taking a look, I hadn't got to it yet!

Agree that integration tests in both frameworks is going to be painful!

>  take a JSON response and try to deserialise it?

This sounds like a reasonable idea - add some more unit tests around deserializing JSON responses
