### ISSUE TITLE
Throttle Search calls to bypass 30 requests / min github limit

### ISSUE THREAD

**Issue by sepharg** [octokit/octokit.net#1711]
Github's search API has a custom limit of [30 requests per minute](https://developer.github.com/v3/search/#rate-limit). 
This makes it very hard to use when making several consequent requests. It'd be great it the Search functionality in octokit would throttle the requests automatically instead of immediately throwing a RateLimitExceeded exception.
Doesn't necessarily need to be the default behaviour, but it's a nice feature to have

**Comment by ryangribble** [comment]
Hi @sepharg, we generally shy away from implementing higher order logic like making composite/multiple API calls on behalf of the consumer, or building in retry/throttling type behaviour in the library itself, because there are too many potential use cases to implement in a way that would suit everyone. 

The rate limit and abuse exception classes should include details on  when it's safe to try again, so consumers can implement their own response to this, in a way that suits their particular implementation.

**Comment by sepharg** [comment]
I see @ryangribble, it´s a fair point.  
The only bad thing is that I doubt we´ll be able to include details when it´s safe to try again because the github api itself doesn´t provide enough information, it just returns a 403 and a generic message.

**Comment by shiftkey** [comment]
> The only bad thing is that I doubt we´ll be able to include details when it´s safe to try again because the github api itself doesn´t provide enough information, it just returns a 403 and a generic message.

[Rate limiting headers](https://developer.github.com/v3/#rate-limiting) are sent on every response from the API. And this is [available from Octokit](https://github.com/octokit/octokit.net/blob/8877eea1cbae447030f15a0b5c50dba7037283a2/docs/getting-started.md#too-much-of-a-good-thing-dealing-with-api-rate-limits) too.

**Comment by StefH** [comment]
Using version 0.40.0 and this code `client.GetLastApiInfo()`

I only get zero's back after the first call?
![image](https://user-images.githubusercontent.com/249938/77535977-d9b93000-6e9b-11ea-9ae7-59a34e452954.png)

**Comment by shiftkey** [comment]
@StefH please open a new issue with details about how to reproduce it (version, code sample, whether you're providing a token or credentials or something else) so we can investigate this properly.
