### ISSUE TITLE
PullRequest.GetAllForRepository doesnt have MergedBy / Comments count

### ISSUE THREAD

**Issue by mikeparker** [octokit/octokit.net#1734]
There seems to be some missing data using GetAllForRepository. I'm writing a slack integration through a .NET core HTTP microservice and I want to summarise all of yesterdays activity, including what pull requests were opened and merged. I have a list of repositories and for each one i do:
```
                    PullRequestRequest options = new PullRequestRequest();
                    options.State = ItemStateFilter.All;
                    var allPrs = await gitHubClient.Repository.PullRequest
                        .GetAllForRepository("MyOrganisation", repository, options);
```
But iterating over the pull requests returned, MergedBy is always null, Comments is always 0, Commits is 0, Additions/Deletions is 0, there are probably other missing fields.

Is this deliberate? Do I need to do something else to fully populate all the data?

**Comment by ryangribble** [comment]
The github API returns sparser results for "GetAll" type queries, so you might need to load each PR individually to have all fields fully populated.

Once you have the list from your search query, try loading each one with `PullRequest.Get()` and check if the fields have the data you want?

If you check out my [Octokit.ReleaseNotes](https://github.com/ryangribble/Octokit.ReleaseNotes) project there is an example of taking a list of PR's and loading all the details about them in parallel which might be useful for you [here](https://github.com/ryangribble/Octokit.ReleaseNotes/blob/master/ReleaseNotes.cs#L278)

**Comment by mikeparker** [comment]
Great, i'll check it out. Thanks for the detailed response. I think it'd be great if there was a way of specifying a fuller return data structure, or even a batch 'fully populate' command, but I'm sure I can work around it with the code you've pasted. Thanks again!

**Comment by ryangribble** [comment]
We try to keep Octokit as an API wrapper that reflects the upstream GitHub API structure and calls, so since the upstream API doesn't have a mechanism to flag that you want "fully populated" responses in "Get All" type requests (presumably for performance reasons), it's not really something that would be implemented in Octokit either.

Note, the successor to the v3 REST API is the [v4 GraphQL API](https://developer.github.com/v4/) and GraphQL allows more control over specifying exactly what fields you want returned in responses etc.  This isnt something we support in Octokit today but is something we are looking at (you of course could talk to it with your own code or another library though)

**Comment by mikeparker** [comment]
Ok great, it looks like GraphQL is the way to go in the future. thanks again
