### ISSUE TITLE
Add GraphQL Node IDs to Models

### ISSUE THREAD

**Issue by grokys** [octokit/octokit.net#1741]
The [`jean-grey` preview](https://developer.github.com/changes/2017-12-19-graphql-node-id/) adds `node_id` fields which expose GraphQL IDs through the REST API. This greatly improves the interop story between REST and GraphQL and is something we will shortly be needing over at [`github/VisualStudio`](https://github.com/github/VisualStudio).

Is this something you'd be interesting in adding? I'd be happy to submit a PR.

**Comment by ryangribble** [comment]
Yep definitely keen to add the `node_id` fields and would be great to get a PR!

Due to the large number of response objects (and even larger number of method calls) that will include this field (and now need to include the `jean-grey` preview header) there is going to be an unfortunate amount of code churn (every Http Get/Post etc will have to specify the accepts header) PLUS all the unit tests have to be adjusted 🤔 

I'd be open to doing this in a more sane way for this sweeping change, until it's out of preview.  Perhaps appending this accepts header onto EVERY call we make, in the `Connection.SendDataInternal()` class could be an option.  This means it's provided on every call and also means unit tests don't need adjusting (because they are testing against the higher level `Connection` methods).  A quick hack doing this shows only 3 unit tests that will need adjusting...

In my previous experience with GitHub API I haven't seen issues when sending accepts headers to calls which don't actually want them (they just appear to be ignored) but I suppose there is some level of risk in doing this on *EVERY CALL*

@shiftkey @kytrinyx what do you think about the risk (or otherwise) of sending the `jean-grey` header on *all* API calls?

**Comment by ryangribble** [comment]
Tagging @gr2m for thoughts on accept header abuse too 😁

**Comment by gr2m** [comment]
My current stance on the preview headers is to be very transparent about it and not to set any preview headers by default. I would make it simple to set them though as end users, including setting multiple headers as they can be combined, so that they are sent with any following request by default

**Comment by bkeepers** [comment]
I agree with @gr2m's stance. However, it'd be nice to give end-users a way of turning this on when instantiating the client. For example, Do any of the clients support something like this?

```rb
client = Octokit::Client.new(:headers => {
  "Accept" => "application/vnd.github.jean-grey-preview+json"
} )
```

**Comment by ryangribble** [comment]
Just to loop back on this one, there are some fundamental differences between octokit.net being a c# based "object oriented" implementation, vs octokit/js being more dynamic that come into play here.  On the javascript side, you can give users control over preview headers if you want, and simply return them back the dynamic json responses without strong typing (assuming even if you wanted to provide typescript typings for the responses, you wouldnt easily be able to support different types of responses (eg Repository and RepositoryWithLicensePreviewEnabled)?

Meanwhile on the c# side here, we are deserializing API responses into explicit response objects that are strongly typed.  This means octokit.net itself pretty much needs to decide if we will enable a preview feature and modify the response object accordingly or not.  It's not really something that could easily be made opt in/out.  In theory for the ones that simply add a field, we could allow opting out of it, and the response object would just have a `null` for the new field.  But sometimes preview features actually change the shape of the response, and we wouldnt be able to support old and new in an elegant way.

In general i think the user base is pretty happy to be ever marching forward, and supporting whatever preview functions come along with the ride 😁 

What I was specifically getting at with looping a few other people into this conversation was my thoughts that to easily implement the graphQL node id on sooo many calls, it would be good if we simply used the preview header on all requests (even those that technically dont support it).  Given the upstream API ignores preview headers that arent relevant to it, this seemed like a pretty pragmatic approach to implement this approach without requiring huge code changes (which would then get reverted when the API is no longer in preview).

**Comment by ryangribble** [comment]
This is out of preview now anyway, so we dont have to worry about the preview header stuff which complicated things given the large number of endpoints 

Now we can simply add the new field to all of the affected response models
