### ISSUE TITLE
Build tooling mismatch

### ISSUE THREAD

**Issue by daveaglick** [octokit/octokit.net#1747]
I _think_ there might be a mismatch between the version of the SDK the build script pulls down and the target. I get the following when trying to build:

```
PS E:\Code\octokit.net> .\build.ps1 -Target Build
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      E:\Code\octokit.net\.dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.4
  - Alternatively, install the framework version '1.1.1'.
dotnet-install: .NET SDK version 1.0.1 is already installed.
dotnet-install: Adding to current process PATH: "E:\Code\octokit.net\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
Restoring packages...
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      E:\Code\octokit.net\.dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.4
  - Alternatively, install the framework version '1.1.1'.
```

And in the `.dotnet` folder I do see `sdk\1.0.1` with `shared\Microsoft.NETCore.App\1.0.4` and not 1.1.1.

**Comment by ryangribble** [comment]
What is your current dotnet DSK installed in the path?

`dotnet --version`

I just tested on a windows machine that has `2.1.2` sdk reported by the above command.  When running the octokit build script it downloads the 1.0.1 runtime into the local `.dotnet` directory and everything proceeds to work fine.  In order to support the `netcoreapp1.0` for AWS Lambda, we did have to use an `ImplicitMetaPackageReference` setting in the csproj files to stop the build tooling automatically going up to a 1.1 equivalent.  It's all clear as mud but would be interested to know what SDK you currently have (and if not at least 2.1.2 like mine, does upgrading your system to the same as my test box, make things work!?)

**Comment by ryangribble** [comment]
Also in my case, after the download of the 1.0.1 framework ps1 file and it executing, the `.dotnet\Shared\Microsoft.NETCore.App\` contains both `1.0.4` and `1.1.1` folders (it sounds like yours only included `1.0.4` for some reason?)

**Comment by daveaglick** [comment]
Interesting - yeah, mine only contained `1.0.4` under the netcoreapp folder. Given that you got both, I wonder if having different global versions changes the local install. Or maybe my work firewall is getting in the way of one or more bits (it’s pretty aggressive).

I think I’ve got the latest SDK, but could be behind a minor release or two. I’ll check next time I’m in front of my workstation and try to figure out what’s actually going on.

**Comment by ryangribble** [comment]
It's funny because I think technically any later sdk could build the projects but in order to execute the test projects (netcoreapp1.0) you need the specific runtime. 

Plus the fact we are using cake frosting as a build script also means you need a runtime for that (and also I just noticed we are targeting netcoreapp1.1 for the cake build project)

Even the fact the build.ps1 wrapper downloads the runtime if you don't already have it is just to try and make things easier rather than just failing and telling the user to go install the right runtime 

We can certainly look into making things a bit more consistent

**Comment by daveaglick** [comment]
`dotnet --version` reports I've got 2.1.4 so I wonder if this may be some kind of regression, though it's not clear to me how the local install of the SDK would impact the bootstrapping process since it downloads it's own SDK.

I'll keep digging. It wasn't a big deal for me personally since I just opened VS and built/tested from there, but now it's a mystery why it's not working and I want/need to get to the bottom of it.

**Comment by daveaglick** [comment]
Turns out it's working fine now that I'm out of the office. I see both the `1.1.1` and the `1.0.4` folders under `,dotnet/shared/Microsoft.NETCore.App` now. I'll attribute this to the aggressive SSL inspection my corporate firewall does - must have blocked one or another of the bootstrapped downloads.
