### ISSUE TITLE
Determine list of folders "changed" between one branch and another.

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1749]
If I have two branches (in some Octokit app) and we know these branches are out of step, is there a way to generate a list of distinct folder names which are involved in all of the difference?

I could easily generate this from the list of files I guess, since their full path will be present.

So better question: is there way to get the list of files involved between these two commits?

Thx

**Comment by shiftkey** [comment]
You probably want the [Compare Commits](https://developer.github.com/v3/repos/commits/#compare-two-commits) API:

`var compare = await client.Repository.Commit.Compare(owner, repo, "master", "branch")`

That will list out the whole file list, and it has some limits which are mentioned in the docs, but that should do the trick.

**Comment by Korporal** [comment]
@shiftkey - Hi,
Im seeing compare results that have non-zero for AheadBy and BehindBy etc - yet the collection "Commits" is always empty, as is "Files", is this expected?

**Comment by ryangribble** [comment]
so is the answer here that in the comparison sense, it doesn report on the commit/file level of the BEHIND changes?  Just like if you have a PR that is behind master, github.com doesnt show you the changes your PR "doesn't" have in it's branches, only "what would change in the base branch if you merge this PR".  Could you diff in the other direction (B->A rather than A->B) if you want to get the reverse changes?

**Comment by Korporal** [comment]
@ryangribble - Yes, "diffing" in reverse is an interesting suggestion, I'll certainly play with that and try to update this issue with what I find.
