### ISSUE TITLE
IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1799]
Is there any merit in adding support for this alternative form of async enumeration?

https://blog.todotnet.com/2017/09/sneak-peek-at-c-8/

Just curious what the core team here think of this.

**Comment by ryangribble** [comment]
Are you suggesting this could be used instead of the normal or `IObservable` clients, or in addition to them?

My *initial* reaction is that I wouldn't be too keen to simply add yet MORE duplicates of every client/method, at least not while we have other higher priority things to implement... however happy to have a discussion about this (or anything really!) if you have further thoughts 😁

**Comment by shiftkey** [comment]
Closing this out for now unless someone is interesting in championing this effort. It'll require a lot of work on internals to support properly alongside the current Task and Observable versions, and I'd rather the maintainers support getting the newer v3 API features supported in the library.
