### ISSUE TITLE
add warning from docs about statistics client data potentially being cached

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1814]
The documentation for the statistics client includes a warning that the data might be cached.
(https://developer.github.com/v3/repos/statistics/#a-word-about-caching)
It might be worthwhile to include that warning or a link to it, in the intellisene on the methods

**Comment by hnrkndrssn** [comment]
I started looking into this, but had a thought before I did any work on it. 

Would it be necessary to have the warning in the intellisense of *every* method (that's a lot of copy-🍝) or would it be enough to add it just to the intellisense of the class and constructor?

**Comment by ryangribble** [comment]
Nobody would really be constructing the `RepositoryStatisticsClient` themselves I dont think, so probably just in the actual class description intellisense would be fine.  I also think this would be fine since that paralllels what the official docs do (a single call out at the top, for the whole client) rather than repeating it on each method :+1:

**Comment by M-Zuber** [comment]
That would show up when a user does `client.RepositoryStatistics` before dotting into an actual method?
If so, then you have my +1
