### ISSUE TITLE
Consider: Dropping .NET 4.5 for 4.5.2

### ISSUE THREAD

**Issue by aidapsibr** [octokit/octokit.net#1817]
Just recently learned that .NET 4.5 in addition to not being supported by Microsoft anymore, does not have a targeting pack available as a distributable. This means, unless I am mistaken, all devs must have Visual Studio installed even if desired code flow is VS Code.

**Comment by ryangribble** [comment]
I've been wondering about these things too.

Given we already have a `netstandard1.1` target, according to the [.NET Standard compatibility matrix](https://docs.microsoft.com/en-au/dotnet/standard/net-standard#net-platforms-support), this alone should already be usable by .NET Framework 4.5 (as long as you use .NET Core SDK 2+ tooling).  So do we even need a `net45` target anymore in the first place?  

I also wonder, if we have the `net45` target for people that somehow cant get off that framework, then is it "just as difficult" for them to move to 4.5.2 as it would be to 4.6+ (in other words is their issue that making ANY changes is not possible)?  

Can you share your use case and project frameworks/versions etc and what restrictions you are operating in?  Also can you see any reason why you wouldnt be able to use the `netstandard1.1` target, and whether that would work in VSCode?

**Comment by psibernetic** [comment]
The issue at hand is `<TargetFrameworks>netstandard1.1;net45</TargetFrameworks>` referencing net45 in a target framework will fail builds if you don't have the targeting pack installed, which isn't available. 

Using netstandard1.1 does work fine, but the package vs framework proliferation is a little ugly honestly, it would look like you are installing a ton of dependencies, but they are just framework redirects. 

For that reason I have been targeting 452 explicitly in my packages, but that causes yet another issue, but one I think you have avoided by targeting so low, but useful info anyway: framework prefers framework, so even on 472 the 45(2) dll will be chosen over any compatible netstandard version. Leads to issues where you may use polyfills for lower framework versions, but desire to use built-in stuff in higher (AsyncLocal for instance). So, then you have to target a higher framework version too.

Also, there is this consideration, semi-related since we are talking about targeting:
![tweet](https://user-images.githubusercontent.com/621605/41524773-6ee0332e-7293-11e8-9e64-e63fe6a2a228.png)

All said my pattern has been: `<TargetFrameworks>netstandard1.X;netstandard2.0;net452;net4X</TargetFrameworks>`  where 4X is the highest framework I would LIKE features from, to omit polyfills if necessary.

**Comment by psibernetic** [comment]
Issue #1745 from January is a pretty prime example of the hassle.

**Comment by ryangribble** [comment]
hmmm so to unpack what you're saying, a full framework app will choose the highest available full framework target but wont ever use a netstandard target even if one exists at a "higher" feature level than the full framework option?  Eg a net472 app choosing a net45 version rather than netstandard2.0? yeesh

Why then wouldnt we actually prefer to only support netstandard1.x and 2.0 and drop net45/452 entirely?  Is it just the "ugliness" of all the included dependencies?  If we had to trade that off against people using later frameworks never being able to tap into the netstandard targets, Im tempted to just do netstandard only?

Is the following the justification you were thinking, as to why you are including each target?

net452 - provide an option for people on "legacy" full framework but prefer the supported 4.5.2 option as well as having a targetting pack available allowing use of vscode etc
net4X - fuller framework offering to not need to use polyfills, full framework apps will prefer this over the net452 target if they can use it
netstandard1.1 - low netstandard offering, based on the concept a library should target the lowest netstandard it can?  Im not seeing much point in having this anymore based on @davidfowl's comment above and the comaptibility matrix showing that everything that can use 1.1 can also happily use 2.0
netstandard2.0 - re-baselining on the fuller API surface, everything that can use 1.1 can also use 2.0 now anyway

**Comment by psibernetic** [comment]
Yeah that my understanding for the most part. 

Only the netstandard2.0 piece is a little confusing. I think you edited to match my understanding, but it is as such: netstandard targets net46+ on the framework side, so if you were only targeting that already in say netstandard1.6 then just re-baseline on 2.0 instead, BUT if you targeted lower, then include both.

So the end result is netstandard1.1;netstandard2.0. 

What I'm not sure about is: does the framework preference issue apply when checking for nuget package updates? If so it could lead to a scenario where clients don't get new package versions until they uninstall and reinstall the package. This is probably worth a test...

**Comment by psibernetic** [comment]
I quickly was able to confirm that issue does not occur, whew!

Also, this is what the experience will look like for framework users when you switch to netstandard only.

![image](https://user-images.githubusercontent.com/621605/41571937-5bdb97fe-732a-11e8-801b-f8ff876b1868.png)

**Comment by davidfowl** [comment]
The experience of installing netstandard 1.x packages on .NET Framework brings up that scary dialog. I've seen projects multi target to net4x and netstandard because of it.

**Comment by ryangribble** [comment]
👋 welcome @davidfowl 

so does that count as "guidance" that the preference is to avoid the scary dialog, thus we should continue to support `net4X` as well as `netstandard1.1`?  

And to clarify your tweet from the other day, we also should add a `netstandard2.0` target to provide a better dependency story for those on newer .NET Core platforms?  And should keep our `netstandard1.1` target since that's the only way people on earlier Mono/Xamarin and .NET Core 1.x can access the library?

Assuming yes, then I guess the result of this Issue discussion is that we should change our current target frameworks (`net45,netstandard1.1`) to `net452,netstandard1.1,netstandard2.0` instead

**Comment by davidfowl** [comment]
> so does that count as "guidance" that the preference is to avoid the scary dialog, thus we should continue to support net4X as well as netstandard1.1?

That might be the least jarring upgrade. I would start with those tfms and test the install on various platforms.

> And to clarify your tweet from the other day, we also should add a netstandard2.0 target to provide a better dependency story for those on newer .NET Core platforms?

Yes. We should do that. The idea is to reduce the dependency closure on .NET Core 2.x and above.

> And should keep our netstandard1.1 target since that's the only way people on earlier Mono/Xamarin and .NET Core 1.x can access the library?

That's an interesting question. You should probably keep it around for now otherwise it'd be a breaking change. At some point though you'll need to cut the cord (like when the support for these older platform runs out).

**Comment by shiftkey** [comment]
We are now targeting .NET Framework 4.6 as a minimum.
