### ISSUE TITLE
explore how we can unify types when generating response types from some schema

### ISSUE THREAD

**Issue by Nezz** [octokit/octokit.net#1855]
I noticed that these two model classes are essentially duplicated:
https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/PullRequestFile.cs
https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/GitHubCommitFile.cs

Is this necessarry? The current setup doesn't make it possible use the two classes interchangeably even though they have the same properties (except for `Filename` and `FileName`).

**Comment by shiftkey** [comment]
For the moment I can live with the duplication of types like this, and I suspect if I can get this code-generation work integrated into the project there will be more cases like this.

> The current setup doesn't make it possible use the two classes interchangeably even though they have the same properties (except for `Filename` and `FileName`).

I suspect both of these are mapped from the `filename` property in JSON, and a change here to correct this would be a breaking change to clients who use these objects. I'd like to be generating these response types from a source of truth first (because I know there will be other cases like this lurking around) before I start publishing breaking changes on callers.

**Comment by shiftkey** [comment]
I've tweaked the description of this issue to indicate where my focus is on the near term.
