### ISSUE TITLE
How to get second last release?

### ISSUE THREAD

**Issue by patricknolan** [octokit/octokit.net#1903]
Hi,

The GitHubClient has a method for getting the Latest Release, however, I need to get the second last release created. Is the only way to achieve this to get all releases and sort by id or date? Would this be hugely inefficient?

**Comment by ryangribble** [comment]
Hi @patricknolan,

Since octokit is a client for the github API, we can't add any method that isn't already provided by github API itself

https://developer.github.com/v3/repos/releases/

So yes to get the 2nd most recent release you would need to use the GetAll method then take the 2nd item. However I don't think you'd need to sort them yourself as the API should already return them in reverse chronological order. Furthermore if you use the `ApiOptions` overload you can request only 1 page of results and that will keep things to an efficient single call (our default behaviour is to loop through and call all pages, so you should use the override to control this)

https://developer.github.com/v3/repos/releases/

**Comment by patricknolan** [comment]
Thanks @ryangribble using the ApiOptions is a good idea.
