### ISSUE TITLE
DateRange does not include time

### ISSUE THREAD

**Issue by patricknolan** [octokit/octokit.net#1904]
Hi,

I'm trying to search for issues and setting the Closed property to a DateRange. However, the value produced by DateRange seems to ignore the Time.

Based on the following link, Time does appear to be supported by the GitHub API.
https://help.github.com/articles/understanding-the-search-syntax/

**Comment by ryangribble** [comment]
Hi @patricknolan 

Yes it does look like we ignore the time component at the moment.  

I'm not sure if this is because the time support was added to GitHub after octokit had implemented request or whether it was just an oversight.

https://github.com/octokit/octokit.net/blob/8407369485541b1fce28f1c9c8d5bf5852579c57/Octokit/Models/Request/SearchRepositoriesRequest.cs#L307-L324

https://github.com/octokit/octokit.net/blob/8407369485541b1fce28f1c9c8d5bf5852579c57/Octokit/Models/Request/SearchRepositoriesRequest.cs#L331

What we could do in order to not affect existing behaviour is keep the existing `ctor`s that accept `DateTime` and mark them `[Obsolete]`, having them continue to only format the query string as YYYYMMDD, then add new `ctor`s that take `DateTimeOffset` types (giving us timezone info as well) and being formatted out to the full ISO8601 timestamp format including time zone info.  

Thoughts?  

If you are keen to send a PR that would be awesome :+1:

**Comment by patricknolan** [comment]
Hey @ryangribble your suggestion solves the issue and is probably the best approach for backwards compatibility. I'll send a PR now.

**Comment by catmorgan** [comment]
This bug still says it is open, but I saw the merged PR. I just updated to Octokit 0.32.0 and I am still experiencing this, but I am using DateRange on the Merged field

**Comment by catmorgan** [comment]
I also noticed that the PR seems to address only  the bug with SearchRepositoryRequest, but I am experience it with SearchIssuesRequest

**Comment by shiftkey** [comment]
Closing this out as we merged #1905, but this hasn't been published to NuGet so we have #1972 open to track that.
