### ISSUE TITLE
Get the content of a specific file

### ISSUE THREAD

**Issue by unruledboy** [octokit/octokit.net#1958]
The GetAll function confuses me. I was hoping to the the content of a specific file only, NOT downloading the contents of any other file in the folder.

Which API should I use? I read through the https://octokitnet.readthedocs.io/en/latest/  but could not find what I want.

**Comment by ryangribble** [comment]
Sorry for the confusion, we are a wrapper/client for the official GitHub API and because this endpoint can return multiple results, our convention is to name it `GetAllxxx`. 

If you specify the file you want in the `path` argument, you will get the contents of that particular file only. 

See the official docs for this endpoint here: https://developer.github.com/v3/repos/contents/#get-contents

**Comment by unruledboy** [comment]
@ryangribble alrighty, all good, I will use it and verify, thanks mate!
