### ISSUE TITLE
EventsClient.GetAllForAnOrganization and EventsClient.GetAllForOrganization methods should have different names

### ISSUE THREAD

**Issue by MikhailTymchukDX** [octokit/octokit.net#1961]
The difference can be seen only when exploring remarks through metadata.
I believe the second method should be named EventsClient.GetAllPublicForOrganization.

**Comment by ryangribble** [comment]
Agree that the naming is a bit confusing, however Im not sure if the suggested renaming makes things much better?!

The `GetAllForOrganization` gets an organization's events whereas the `GetAllForAnOrganization` gets a user's events for an organization.  

https://developer.github.com/v3/activity/events/#list-events-for-an-organization
> List events for an organization
> This is the user's organization dashboard. You must be authenticated as the user to view this.

**Comment by MikhailTymchukDX** [comment]
Ok, let's rename `GetAllForAnOrganization` into `GetUserEventsForAnOrganization`?

**Comment by ryangribble** [comment]
To keep with convention we should use `GetAll`...

Some of the other methods in this class are like `GetAllUserPerformed()` so potentially this could be `GetAllUserPerformedForOrganization()` ?

I think part of the problem here is that the API doc isnt clear on exactly what events this call DOES return!  It says "the users organization dashboard" - what is this?  Is this only events performed by this user in the specified organization or does it include other events in the organization (eg if an issue was opened or whatever)?

**Comment by ryangribble** [comment]
Poking the API I see comments made by you and me, things created/deleted in other repositories in this organization etc.  

So its deifnitely not events "performed" by the user but more so events "for" the user, and scoped to the organization in question.

So how about we go with the name `GetAllForUserInOrganization()` and we update the metadata XmlDoc summary wording to "Gets all the events shown on a user's organization dashboard"?

**Comment by MikhailTymchukDX** [comment]
>So how about we go with the name GetAllForUserInOrganization() and we update the metadata XmlDoc summary wording to "Gets all the events shown on a user's organization dashboard"?

Agree. That's much clearer name. Thanks!
