### ISSUE TITLE
Milestone is missing ID

### ISSUE THREAD

**Issue by patriksvensson** [octokit/octokit.net#1970]
It looks like `Id` is missing from `Octokit.Milestone`.

API example can be seen here: https://developer.github.com/v3/pulls/#get-a-single-pull-request

**Comment by shiftkey** [comment]
@patriksvensson what did you need `Id` for? I believe that's an internal identifier for it, and `Number` is the public-facing ID that you should use when querying, based on https://developer.github.com/v3/issues/milestones/#get-a-single-milestone

**Comment by patriksvensson** [comment]
I use it as an external identifier in a GitHub client i'm building.

What is the practice when it comes to expose the id field? A lot of other entities in the Octokit API exposes it (label, issue, pullrequest) and it's part of the public API.

I would gladly submit a PR for this.

**Comment by shiftkey** [comment]
> What is the practice when it comes to expose the id field?

Some entities can be queried for using the `id`, but the only entity I can think of where this is explicitly support is for repositories and users - because they can renamed or transferred, integrators can query for that as it's considered more "stable". You'll also see these URLs in the pagination response to indicate there are more results, but it's not used much these days.

But for repository-specific entities (issues, labels, milestones, etc) I don't believe the same lookup was ever implemented.

> I would gladly submit a PR for this.

I'm not opposed to this, but I just wanted to indicate that the field is not what is used in the API itself.

cc @ryangribble just in case.

**Comment by ryangribble** [comment]
If it's in the public API response payload I don't mind having it implemented here for completeness

**Comment by hnrkndrssn** [comment]
@patriksvensson would you still like to submit a PR for this? Otherwise, I'll be happy to tackle it over the weekend.
