### ISSUE TITLE
How select where need send verify code?

### ISSUE THREAD

**Issue by MairwunNx** [octokit/octokit.net#1975]
During verification, I want the user to be able to choose where to send the verification code. Of the options are: application and SMS.

Usually, if an application is attached (for example, like mine: Google Authenticator), then the verification code will be automatically expected from the application, but what if the user wants to log in via SMS?

On the GitHub website, you can choose where to send the code. I saw that in the API there are headers working with this, but where is it in octokit.net api?

Thanks.

**Comment by MairwunNx** [comment]
I didn’t dig into the issues of the GitHub desktop not long ago, and I saw that there was such a problem. After reading it, I realized that in octokit.net such a function is not implemented, but it can be achieved by adding some parameters to the headers. I will not close this problem, if someone realizes the opportunity to choose where to send the confirmation code. ☺

**Comment by shiftkey** [comment]
> I saw that in the API there are headers working with this, but where is it in octokit.net api?

The headers are sent as part of the response when the authentication fails because of a 2FA challenge, and are detailed here: https://developer.github.com/v3/auth/#working-with-two-factor-authentication

> `X-GitHub-OTP: required; SMS` or `X-GitHub-OTP: required; app`

There is no way in the GitHub API to control which method is chosen, you simply need to get the code from the user to perform 2FA. If you are implementing authentication in an app you need to prompt the user, based on what method is being asked by GitHub.
