### ISSUE TITLE
Get All Issues and keep them in synch

### ISSUE THREAD

**Issue by apobekiaris** [octokit/octokit.net#1983]
are there any recommendation to this? getting all issues is pretty straight forward, but what the recommended approach to keep them in synch?

**Comment by shiftkey** [comment]
@apobekiaris I don't have a specific solution here, but some thoughts based on my experience:

 - the issues API supports a `since` parameter that will return issues only updated since a certain time - that's helpful to exclude issues that haven't changed
 - the `number` field returned on an issue is the value shown to users and in URLs, and I'd use that to track each record - so if issue number `20` was updated I'd use that and overwrite whatever you have cached locally that's also issue number `20`

Hope that helps, and good luck!
