### ISSUE TITLE
PullRequestReview is missing User

### ISSUE THREAD

**Issue by patriksvensson** [octokit/octokit.net#1984]
Hello!

First let me thank you for an awesome library! This have made my life so much easier the last couple of months.

I just released an application which use Octokit under the hood, and when following up on some telemetry I see that some users experience some problems when retrieving reviews. To be precise, it seems like a review can be created without a user (`PullRequestReview.User` is `null` or `PullRequestReview.User.Login` is null).

Is there a scenario where a GitHub pull request could be created without a user, or might this be a bug in Octokit?

**Comment by shiftkey** [comment]
> To be precise, it seems like a review can be created without a user (`PullRequestReview.User` is `null` or `PullRequestReview.User.Login` is null).

I've not stumbled upon this case, but if you've got some known cases that are causing issues I'd reach out to [GitHub Support](https://github.com/contact) as they'll be able to escalate it to the team that looks after this area.

**Comment by patriksvensson** [comment]
Hello,

All the telemetry I get back is 100% anonymous so I don't have a repro for this (and I've never experienced it myself so might never have).

Just wanted to check with someone at Github and ask if this is something that can be expected by the GitHub API (since it's not mentioned in the documentation), but I'll reach out to the support as you suggest and see if they can answer it. :+1:

**Comment by gep13** [comment]
@patriksvensson depending on what exactly you are doing, I might have seen something "similar".

When attempting to find all the people who have worked on a release of Cake, we have found that the `Author` of a commit can be null.  This has been traced back to the scenario where the email address associated with a commit (i.e. the local email address configured in the users git client), isn't a verified email address of a User on GitHub.  In this scenario (when a user is likely using an internal email address, and used it by mistake when contributing to an open source project), we have had to handle the fact that Author can be null, and instead, revert to using the raw `Name` attribute of the commit, rather than the GitHub user.

It would be nice in this scenario if there were a property which said `VerifiedUser` or similar.

Could be that this is a similar problem to what you are seeing.

**Comment by patriksvensson** [comment]
@gep13 That makes absolutely sense. I wonder if this could happen for reviews if the user deleted their account or something similar? Afaik you cannot create a review without being logged in to GitHub? Or maybe my assumptions are incorrect here...
