### ISSUE TITLE
Out-of-date library

### ISSUE THREAD

**Issue by hrytskivr** [octokit/octokit.net#1986]
This library is cool, but it is out of date. When are you going to implement draft-pull-requests for example? It was introduced back in February - it is a long long time ago. Is GitHub responsible for this library at all or it is completely up to enthusiasts to maintain it and keep it up to date?

**Comment by shiftkey** [comment]
@hrytskivr thanks for the feedback!

> This library is cool, but it is out of date.

It's been [about a year](https://www.nuget.org/packages/Octokit/0.32.0) since our last release to NuGet, and [there's plenty of work sitting on `master`](https://github.com/octokit/octokit.net/compare/v0.32.0...master) that hasn't been published, so I'll put this on my to-do list for the weekend or next week.

> When are you going to implement draft-pull-requests for example?

We track support for new API changes as issues, and https://github.com/octokit/octokit.net/issues/1945 is the discussion about this. It did have some interest in submitting a contribution but that seemed to have trailed off. Maybe it's worth checking in with that discussion to see if it can be moved along?

> Is GitHub responsible for this library at all or it is completely up to enthusiasts to maintain it and keep it up to date?

I helped spin this out of an internal product years ago so the community could use it, and @ryangribble (who is not staff) has been a great maintainer of it in recent times, but due to our available bandwidth these days we do rely on external contributions if users want to see specific features supported.

We're happy to answer questions and make time for reviews, but there's a non-trivial amount of overhead dealing with new issues and reviewing contributions these days.

**Comment by hrytskivr** [comment]
OK, got it, thanks for your reply!
