### ISSUE TITLE
Throw NotFoundException when a commit is not found for .netstandard

### ISSUE THREAD

**Issue by rakeshvanga** [octokit/octokit.net#2026]
```
try
{
    var master = "cda714bef60d3c787ee3db2512025cde46d02dba"; // some valid commit
    var commit = await client.Repository.Commit.Get("octokit", "octokit.net", master + "777");
}
catch (Octokit.ApiValidationException ex)
{
  // handle commit not found
}
```
Using a .NetCore 3.0 MVC web app. Whenever a commit is invalid, the octokit client is throw `Octokit.ApiValidationException` with the message `No commit found for SHA: cda714bef60d3c787ee3db2512025cde46d02dba777`.

Suggestion: 
Consider throwing Octokit.NotFoundException here so that there would be no need to check the message of the ApiValidationException to understand whether the commit is valid or not.

**Comment by shiftkey** [comment]
@rakeshvanga thanks for the feedback

> Consider throwing Octokit.NotFoundException here so that there would be no need to check the message of the ApiValidationException to understand whether the commit is valid or not.

These exceptions are thrown based on the status code that the GitHub API raises:

 - `NotFoundException` -> HTTP 404 Not Found
 - `ApiValidationException` -> HTTP 422 Unprocessable Entity

I believe this is occurring because it's falling back to trying to using string as a SHA, which is failing because it's not the expected format:

```json
{
  "message":"No commit found for SHA: master777",
  "documentation_url":"https://developer.github.com/v3/repos/commits/#get-a-single-commit"
}
```

The client itself is just parsing the response we get and converting it to an exception based on the status code, so I'd recommend either handling this error or using the `RepositoryBranchesClient` that can resolve a branch (or error) for you:

```
var branch = await github.Repository.Branch.Get("octokit", "octokit.net", "master777");
```

This will 404 when it can't find the branch, and the error aligns better with what the API expected:

```json
{
  "message":"Branch not found",
  "documentation_url":"https://developer.github.com/v3/repos/branches/#get-branch"
}
```

**Comment by rakeshvanga** [comment]
@shiftkey Thanks for the details and suggestion. I would rather catch the `ApiValidationException` and handle accordingly than going with a different API.
