### ISSUE TITLE
Search requests need to correctly encode offset for date values

### ISSUE THREAD

**Issue by kceiw** [octokit/octokit.net#2056]
Test version 0.36.0

The repro snippet
```
            var endDate = new DateTimeOffset(2012, 12, 20, 16, 0, 0, TimeSpan.FromMinutes(8 * 60)); // offset +08:00
            var startDate = endDate.AddDays(-30);
            var request = new SearchRepositoriesRequest()
            {
                Updated = DateRange.Between(startDate, endDate)
            };
            var githubClient = new GitHubClient(new ProductHeaderValue("MyAmazingApp"));
            var repos = githubClient.Search.SearchRepo(request).Result;
            Console.WriteLine($"ReproCase: Find {repos.TotalCount} repos");
```

That is becoming to a http request using this url (from Fiddler)
`https://api.github.com/search/repositories?page=1&per_page=100&order=desc&q=pushed:2012-11-20T16:00:00+08:00..2012-12-20T16:00:00+08:00`

Note that "+" isn't escaped in this case and it only finds zero repositories.

Escaping "+" to "%2B" in a browser gets me total_count 98777

`https://api.github.com/search/repositories?page=1&per_page=100&order=desc&q=pushed:2012-11-20T16:00:00%2B08:00..2012-12-20T16:00:00%2B08:00`

I attach a .NET core project to demonstrate it.
[OctokitRepro.zip](https://github.com/octokit/octokit.net/files/4003519/OctokitRepro.zip)

**Comment by shiftkey** [comment]
@kceiw this sounds like we should be either encoding here

https://github.com/octokit/octokit.net/blob/e9409e0cb5759566c9f13779b8f9431c8230df8f/Octokit/Models/Request/SearchRepositoriesRequest.cs#L164-L167

Or more likely inside `DateRange` itself:

https://github.com/octokit/octokit.net/blob/fd6bca910cce936d84af7fb264b516bff3904c57/Octokit/Models/Request/SearchRepositoriesRequest.cs#L294-L300

Marking this one as Up for Grabs because I think once we confirm the encoding change this is an easy fix to verify.
