### ISSUE TITLE
Q: Can Octokit authentication against GitHub leverage the private/public key configured for git?

### ISSUE THREAD

**Issue by JackFreelanderHBO** [octokit/octokit.net#2059]
Apologies if this is a duplicate issue, the closest I could find is https://github.com/octokit/octokit.net/issues/930 which isn't quite the same question, but it is also in the realm of authentication.

As part of a developer workflow I would like to add some logic which uses octokit REST APIs to query GitHub to check open pull requests.  In order to do this, it seems, I need to require _every_ developer to go to GitHub to generate a personal access token (with at minimum 'repo') scope, and store that token locally (per host).

The developers have _already_ configured a public/private key for git (the command line).  I would like to leverage the existing private/public key that developers have set up for git auth to use with octokit, and I would like to avoid having to ask every single user to create a personal access token for accessing *GitHub* (explaining the difference between git vs. GitHub to several hundred users is not something I have any desire to do).

Is there any way that octokit can or will soon support this?

**Comment by Dagizmo** [comment]
Octokit is just a wrapper of the GitHub API, to use the GitHub API you need to provide your own tokens, so that would be the case for octokit, you could make another application that does get the configuration locally.

**Comment by shiftkey** [comment]
> I would like to leverage the existing private/public key that developers have set up for git auth to use with octokit, and I would like to avoid having to ask every single user to create a personal access token for accessing _GitHub_ (explaining the difference between git vs. GitHub to several hundred users is not something I have any desire to do).

SSH authentication is not supported in Octokit because we are limited by what the GitHub API supports for authentication. The only supported methods are Basic Authentication (discouraged for security reasons, and some APIs will reject basic authentication), and Tokens (either Personal Access Token or OAuth apps).

If you're wanting to make API calls on behalf of a user, I'd recommend creating an OAuth app for your organization as it avoids the need for the user to create a PAT, defers authenticating the user to GitHub, and users can see and revoke the permission in the future.

But it sounds like you want this to work on the user's local machine, which is a different workflow that doesn't work best with OAuth.
