### ISSUE TITLE
404 Not Found when creating issue with Octokit

### ISSUE THREAD

**Issue by panthersdude2001** [octokit/octokit.net#2061]
All,
I am having trouble making a new issue with your program.
It says 404 Not found with this stack trace
![wct error](https://user-images.githubusercontent.com/44646536/72688888-b9ef3f80-3ad9-11ea-9a18-fec9bd91c391.png)
The code is as follows, which is copied verbatim from the manual
```
Dim gh As New GitHubClient(New ProductHeaderValue("removedforprivacy"))
Dim rh = New NewIssue(SystemInformation.UserName & " has a problem - The error was: " & ExceptionLabel.Text)
Dim r = gh.Issue.Create("idremovedforprivacy", rh)
MessageBox.Show("Thank you. Your error report has been sent. You can follow the status of this issue by visiting our project page and referencing issue no. " & r.Result.Title & ". The program will now close.", "Error Report Sent!", MessageBoxButtons.OK, MessageBoxIcon.Information)
System.Windows.Forms.Application.Exit()
```

Is this a user issue or is this a problem with Octokit?

**Comment by shiftkey** [comment]
@panthersdude2001 the "Not Found" error is being returned because the GitHub API returned a 404, which generally occurs when it can't find a repository.

There's some extra things that you should check that might be responsible for the failure:

 - repository - ensure that the repository exists and the user has permissions to access it
 - authentication - issue creation requires the client to have a token set, but it's not clear from the example that you are doing that
 - token scope - if you are assigning a token to the `GitHubClient`, ensure that it has the right permissions (`public_repo` scope is needed if the repository is public, `repo` if it's a private repo)

**Comment by panthersdude2001** [comment]
Oh didn't see that with the authentication and token scope.
Let me try that and report back the results.

**Comment by panthersdude2001** [comment]
And it works! Thank you!
Closing
