### ISSUE TITLE
Attempted Use With Blazor wasm return "Property AllowAutoRedirect is not supported."

### ISSUE THREAD

**Issue by microhobby** [octokit/octokit.net#2188]
I am trying to use the library with Blazor wasm template but this returns the stack:

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Property AllowAutoRedirect is not supported.
System.PlatformNotSupportedException: Property AllowAutoRedirect is not supported.
  at System.Net.Http.HttpClientHandler.set_AllowAutoRedirect (System.Boolean value) <0x2149488 + 0x0000c> in <filename unknown>:0 
  at Octokit.Internal.HttpMessageHandlerFactory.CreateDefault (System.Net.IWebProxy proxy) <0x212fa80 + 0x00012> in <filename unknown>:0 
  at Octokit.Internal.HttpMessageHandlerFactory.CreateDefault () <0x212f5f8 + 0x00002> in <filename unknown>:0 
  at Octokit.Internal.HttpClientAdapter..ctor (System.Func`1[TResult] getHandler) <0x212f248 + 0x00020> in <filename unknown>:0 
  at Octokit.Connection..ctor (Octokit.ProductHeaderValue productInformation, System.Uri baseAddress, Octokit.ICredentialStore credentialStore) <0x212eb70 + 0x0001c> in <filename unknown>:0 
  at Octokit.Connection..ctor (Octokit.ProductHeaderValue productInformation, System.Uri baseAddress) <0x2129d58 + 0x00010> in <filename unknown>:0 
  at Octokit.GitHubClient..ctor (Octokit.ProductHeaderValue productInformation) <0x2121108 + 0x0000c> in <filename unknown>:0 
  at microhobby.Pages.Index.OnAfterRenderAsync (System.Boolean firstRender) <0x20f4e28 + 0x00034> in <filename unknown>:0 
```

I know this must be a limitation of Blazor wasm. But I'm curious if anyone has the same problem and if there is any workaround. Or if we should open an issue in the dotnet project (I really don't know why AllowRedirect is not supported by Blazor wasm)

**Comment by shiftkey** [comment]
>  Or if we should open an issue in the dotnet project (I really don't know why AllowRedirect is not supported by Blazor wasm)

@microhobby let's start from there, as I don't have much control over `HttpClientHandler` and how it can be used from Blazor.

The relevant code is here:

https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Http/HttpMessageHandlerFactory.cs#L18-L21

**Comment by HasinduLanka** [comment]
Exactly same bug here :-(

**Comment by shiftkey** [comment]
@HasinduLanka I need more information to understand the problem you're seeing

**Comment by HasinduLanka** [comment]
When you try to authenticate Octokit in blazor, which runs on .net standard framework, you get the above error
 This page gives an answer
 https://stackoverflow.com/questions/46400797/httpclienthandler-throwing-platformnotsupportedexception


It seems aws are also getting the same problem
 https://github.com/aws/aws-sdk-net/issues/1307

**Comment by shiftkey** [comment]
The only area I'm aware of where we enable these in the library is here:

https://github.com/octokit/octokit.net/blob/69d118230d89f97e59305108adcac508a60e3566/Octokit/Http/HttpClientAdapter.cs#L30-L53

This is only enabled for `net46`:

https://github.com/octokit/octokit.net/blob/fe6639f270aa20f83a3fa6d47c88315d2c340eef/Octokit/Octokit.csproj#L27-L29

This shouldn't be enabled for .NET Standard as we don't include that `ifdef`.

**Comment by HasinduLanka** [comment]
I was playing with this error for few hours.

Things I saw,

- Create .net standard 2.0 project, refer octokit.net nuget and consume it -> WORKS  
- Create .net standard 2.1 project (like Blazor wasm), refer octokit.net nuget, consume it with a .net core 3.1 app -> WORKS  
- Create .net standard 2.1 project (like Blazor wasm), refer octokit.net nuget, consume it -> ERROR  
`Property AllowAutoRedirect is not supported.
System.PlatformNotSupportedException: Property AllowAutoRedirect is not supported.
  at System.Net.Http.HttpClientHandler.set_AllowAutoRedirect (System.Boolean value) <0x2149488 + 0x0000c> in <filename unknown>:0 `

- Clone this repo, Remove `AllowAutoRedirect = false` from HttpMessageHandlerFactory.cs, Consume it with a .net standard 2.1 project (like Blazor wasm)  -> Above error is gone, But It does not really Authenticate GitHubClient on 
            `Client = new GitHubClient(new ProductHeaderValue("Product Name"))
            {
                Credentials = new Credentials(username, password)
            };`

So I get 
`Octokit.AuthorizationException: Bad Credentials
  at Octokit.Connection.HandleErrors (Octokit.IResponse response) [0x00018] in 
 <PATH>\octokit.net\Octokit\Http\Connection.cs:686`

It's framework issues, I'm very thankful for helping us on these :-)

**Comment by HasinduLanka** [comment]
It looks like Blazor Web Assembly doesn't have AllowAutoRedirect property because HttpClientHandler is implemented via JavaScript APIs. Help please!

**Comment by martinmthomas** [comment]
@HasinduLanka, I agree with your observation on why `AutoRedirect` does not work in Blazor. Also see [#16955](https://github.com/dotnet/aspnetcore/issues/16955). Though this is marked as closed, you can see that there are still open comments about it. To workaround this, the best way is to remove the `AutoRedirect` property in the `HttpMessageHandlerFactory.cs` file and not setting it to True. For whatever reason, Blazor does not like we setting the value (even if it is the default value) to this property. Also, you can remove the default handler completely when creating HttpClient instance but this prevents additional code in the default handler which might work. 

I assume there must be a reason why Octokit prevents `AutoRedirect` in the implementation. It is better if someone can explain that so that you are not creating any other issue down the line by enabling it.

As with the auth issue, I suppose it is because [Basic Auth is deprecated](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/). I have tried with my Personal Access Token and it is working for me. I used below syntax 
```
var github = new GitHubClient(new ProductHeaderValue("Product Name"))
        {
            Credentials = new Credentials("Provide_PersonalAccessToken_Here", AuthenticationType.Bearer)
        };
```
It might be worth retrying with a PAT after 2FA is enabled just to see if it is an issue with Basic Auth.

**Comment by shiftkey** [comment]
> I assume there must be a reason why Octokit prevents `AutoRedirect` in the implementation. It is better if someone can explain that so that you are not creating any other issue down the line by enabling it.

@martinmthomas from memory this is still kept around due to behaviour around edge cases that have built up over the years:

https://github.com/octokit/octokit.net/blob/b9d1f448d49cbcdcd18208aa445458785581f7bd/Octokit/Http/HttpClientAdapter.cs#L225-L252

The [blame for this file](https://github.com/octokit/octokit.net/blame/b9d1f448d49cbcdcd18208aa445458785581f7bd/Octokit/Http/HttpClientAdapter.cs) has more context and links to the relevant commits, and I think there were cases around us having to explicitly handle things better than the defaults on Windows (where this library originated) that may no longer be necessary.

**Comment by HasinduLanka** [comment]
### Everyone, thank you very much - Issue is fixed!

Just like @shiftkey said **I removed the line ` AllowAutoRedirect = false `** from HttpMessageHandlerFactory.cs  

Then octokit didn't authenticated because, HTTPClient get redirected and doesn't return the correct result back when using **password** authentication.  

But just like @martinmthomas said, **this doesn't occur in Personal Token Based Auth**. So using token instead of password allowed me to Authenticate without any error.   

_p.s. I'll make this repo public as soon as our 'Account servers' are ready. So anyone could cope with this_  

Again thanks for quick help!

**Comment by AngelaMay27** [comment]
> I am trying to use the library with Blazor wasm template but this returns the stack:
> 
> ```
> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
>       Unhandled exception rendering component: Property AllowAutoRedirect is not supported.
> System.PlatformNotSupportedException: Property AllowAutoRedirect is not supported.
>   at System.Net.Http.HttpClientHandler.set_AllowAutoRedirect (System.Boolean value) <0x2149488 + 0x0000c> in <filename unknown>:0 
>   at Octokit.Internal.HttpMessageHandlerFactory.CreateDefault (System.Net.IWebProxy proxy) <0x212fa80 + 0x00012> in <filename unknown>:0 
>   at Octokit.Internal.HttpMessageHandlerFactory.CreateDefault () <0x212f5f8 + 0x00002> in <filename unknown>:0 
>   at Octokit.Internal.HttpClientAdapter..ctor (System.Func`1[TResult] getHandler) <0x212f248 + 0x00020> in <filename unknown>:0 
>   at Octokit.Connection..ctor (Octokit.ProductHeaderValue productInformation, System.Uri baseAddress, Octokit.ICredentialStore credentialStore) <0x212eb70 + 0x0001c> in <filename unknown>:0 
>   at Octokit.Connection..ctor (Octokit.ProductHeaderValue productInformation, System.Uri baseAddress) <0x2129d58 + 0x00010> in <filename unknown>:0 
>   at Octokit.GitHubClient..ctor (Octokit.ProductHeaderValue productInformation) <0x2121108 + 0x0000c> in <filename unknown>:0 
>   at microhobby.Pages.Index.OnAfterRenderAsync (System.Boolean firstRender) <0x20f4e28 + 0x00034> in <filename unknown>:0 
> ```
> 
> I know this must be a limitation of Blazor wasm. But I'm curious if anyone has the same problem and if there is any workaround. Or if we should open an issue in the dotnet project (I really don't know why AllowRedirect is not supported by Blazor wasm)

🙂

**Comment by AngelaMay27** [comment]
🙂

**Comment by johan-v-r** [comment]
Seems very much related to this dotnet/runtime issue: [[wasm] Blazor 303 responses, and fetch vs navigation #39365](https://github.com/dotnet/runtime/issues/39365)
