### ISSUE TITLE
Discrepancy: WatchersCount vs Activity.Watching.GetAllWatchers

### ISSUE THREAD

**Issue by SeanKilleen** [octokit/octokit.net#2208]
Follow-up to #2182.

Hi @shiftkey @KarolGrzesiak,

Thanks for putting in a PR to return the watchers count on the repository object. I was just on a stream the other day talking about how it could save me a bunch of API calls, and then there it is. :) 

I noticed a strange discrepancy and I want to make sure I'm understanding correctly.

Should Repository.WatcherCount be expected to contain the same results as ` _githubClient.Activity.Watching.GetAllWatchers(repoId);` ?

I've noticed that `Repository.WatcherCount` and utilize the Activity API appear to produce different results. And in the cases where they differ, the Activity API appears to be returning the count that I see in the UI for watchers. 

Do you have any thoughts on why this might be? Do they have two different intended purposes and are named similarly?

**Comment by shiftkey** [comment]
@SeanKilleen is there a public repository you can share that illustrates the problem? (or was showing the issue?)

The first thing that comes to mind here is caching, with three potential ways to get this number:

 - `watchers_count` on the repository returned via the API could be cached for a period of time because of all the different places in the GitHub API where `repository` is used
 - enumerating the [List Watchers](https://developer.github.com/v3/activity/watching/#list-watchers) API would require getting the latest details about each watcher, and thus is more likely to be correct (but slower)
 - but if the website is showing a different watchers count it could be computing this in a different way to the API

**Comment by SeanKilleen** [comment]
@shiftkey https://github.com/excellalabs/konmaripo would work (if you provide a key/orgName in settings, and disable the auth). I'll try to get a simpler repro. I've linked the PR at https://github.com/excellalabs/konmaripo/pull/63 as well; the current state of that PR has both data points showing side by side in the details page for a given repository. I'll try to do a PR off of my PR so that you can just provide a key & orgName and not muck around with other stuff.

I think I've ruled out caching as a consideration on my end because this is happening on startup of the app on first view (we retrieve the list of repositories and there's another "detail" page where I provide the results of getting watchers via the activity API). The summary page is returning Watcher.

I'd expect GitHub caching wouldn't be relevant here. This is a tool to archive old repos, and some of these watchers haven't changed for years so I imagine would be showing up.

Although...maybe it's *because* the repos in question are old that the WatcherCount property is smaller than I'd expect?

**Comment by SeanKilleen** [comment]
@shiftkey repro branch here: https://github.com/excellalabs/konmaripo/tree/repro-for-octokit-issue-2208

Requires you to input AccessToken and OrganizationName in appSettings or user secrets.

**Comment by shiftkey** [comment]
What's wild about your repo is that the field we're supposed to be deprecating is correct when looking at it directly from the API `https://api.github.com/repos/excellalabs/konmaripo`:

```json
  "watchers_count": 0,
   ...
  "subscribers_count": 3
```

I was under the impression that we were standardizing on one value here, but the [example repo](https://developer.github.com/v3/repos/#get-a-repository) in our docs makes me wonder if they're actually different underneath, and this is just some confusion between the API and the website itself.

Also, the [List Watchers API](https://developer.github.com/v3/activity/watching/#list-watchers) is actually described as `GET /repos/:owner/:repo/subscribers` and in your situation `https://api.github.com/repos/excellalabs/konmaripo/subscribers` returns the 3 entities. 

So maybe `watchers_count` is actually the value that we're supposed to obsolete? I need to investigate some more because it's all rather fuzzy right now...

**Comment by SeanKilleen** [comment]
> So maybe watchers_count is actually the value that we're supposed to obsolete?

I think you're on to something there. Mostly I'm relieved that it's at least stumped you temporarily too. 😆

**Comment by SeanKilleen** [comment]
> What's wild about your repo is that the field we're supposed to be deprecating is correct when looking at it directly from the API https://api.github.com/repos/excellalabs/konmaripo

Ah, to be clear, this repo isn't the one with the incorrect count. It's the one with the project that is utilizing the API. May be worth confirming the repro steps against the branch I linked. 

(This is not urgent by the way. I appreciate you jumping on it so quickly but if you need to return to it later I understand.)

**Comment by SeanKilleen** [comment]
One other theory I'm going to follow up on but dropping here:

This org is a private org and some people have since moved on. I wonder if it's possible that the watchers list contains people who no longer have access, and so the effective Watcher count is therefore smaller.
