### ISSUE TITLE
SearchIssuesRequest doesn't support phrase

### ISSUE THREAD

**Issue by patricknolan** [octokit/octokit.net#2234]
Should the SearchIssuesRequest support the searching of a phrase? 

If I have an issue with the phrase "hello world" in the body, the following query does not return the issue

`SearchIssuesRequest request = new SearchIssuesRequest("hello world");
request.In = new[] { IssueInQualifier.Body };
request.Repos.Add("repo name");`

However, the following query does return the issue

`SearchIssuesRequest request = new SearchIssuesRequest("hello");
request.In = new[] { IssueInQualifier.Body };
request.Repos.Add("repo name");`

Should I be able to search a phrase or can I only search one distinct word?

**Comment by minhhieugma** [comment]
@patricknolan you have to put the phrase inside a double quote.
For example:

```
SearchIssuesRequest request = new SearchIssuesRequest("\"hello world\""); 
```

I know it's weird. I think I will try to make a PR to cover it and auto-add the quote somehow. If not, at least we need to update the documentation.
@nickfloyd

**Comment by minhhieugma** [comment]
I found some interesting things:
- The GitHub API that GitHub provides doesn't work the same as what they actually use on the GitHub website.
- That's why with a given input, we might have different results.

I realize that GitHub API has difficulty to parse the query if  we add extra information such as `user:xxx`

For example, 

Not work 1 -  Return wrong data
```
CreateHostBuilder(args).Build().Run();+user:minhhieugma
```

Not work 2 -  Return wrong data
```
CreateHostBuilder(args).Build().Run(); user:minhhieugma
```

Not work 3 -  Return error
```
"CreateHostBuilder(args).Build().Run();" user:minhhieugma
```

Work
```
user:minhhieugma CreateHostBuilder(args).Build().Run();
```
