### ISSUE TITLE
Can not resolve PullRequestReviewComment

### ISSUE THREAD

**Issue by joscol** [octokit/octokit.net#2324]
PullRequestReviewComment does not contain the resolved state of the comment and there is no way to resolve a comment.

**Comment by mireedmsft** [comment]
@joscol @shiftkey Per offline discussion this will require adding a REST API to resolve a comment (in addition to the existing GraphQL api) since oktokit.net wraps the REST API only. Current internal guidance is that engineering effort should be spent on GraphQL, so I doubt we'll get to the point where we can do this in Oktokit.net unfortunately.
