### ISSUE TITLE
Is ocotkit.net still maintaind?

### ISSUE THREAD

**Issue by CaptainAchilles** [octokit/octokit.net#2347]
I have not seen anything merged or released in quite a while. Is this package still maintained?

**Comment by SeanKilleen** [comment]
Yes, the package is maintained with love and care but releases have slowed due to other legitimate obligations on behalf of the maintainers (I'm not one of them but have seen their activity). 

I'd love to see others commit to actively maintaining this project as I think more maintainers prevents burnout, but the current maintainers have stewarded this project well so I'm comfortable deferring to them.
