### ISSUE TITLE
The GetAllRepositories method raises an exception

### ISSUE THREAD

**Issue by AndreyKozhevnikov** [octokit/octokit.net#2368]
Hello,

We have the organization: 
"DevExpress-Examples"
In this organization we have the group:
"Maintain Group" (id 2662639)
In this group, there are over 5k repositories.

Octokit.GitHubClient

When I try to get all repositories from this group using the following code:
`var teamGitRepos = client.Organization.Team.GetAllRepositories(gitTeam.Id).Result;`
I get the exception:
![image](https://user-images.githubusercontent.com/14300209/137485624-b68395ac-b946-4398-a08c-acced4510a3c.png)

**Comment by JonruAlveus** [comment]
Hi @AndreyKozhevnikov, sorry for the slow reply. I've done a bit of reading and other people were suffering because of additional request headers being sent at the same time (not sure I understand that, but apparently that was it). We have recently removed the additional rest headers here. Are you able to use the latest version of this project and try again to see if it's fixed for you?
