### ISSUE TITLE
any plans to add ApiOptions to Repository.GetAllPublic ?

### ISSUE THREAD

**Issue by git37** [octokit/octokit.net#2369]
in order to allow pagination?

**Comment by JonruAlveus** [comment]
Hi @git37, very sorry for the slow reply. Unfortunately there's not a lot we can do around pagination on that endpoint. Github only provide us with a "since" parameter, so we can't change page size. Currently the code gets all results available. Were you looking to only retrieve a subset of pages? We could potentially allow you to retrieve only the first 5 or the first 10 pages of results?
