### ISSUE TITLE
How to authenticate if the user is valid or not with username and personal access token using octokit library

### ISSUE THREAD

**Issue by Sjaiswal08** [octokit/octokit.net#2599]

**Comment by nickfloyd** [comment]
Hey @Sjaiswal08, thanks for reaching out.  When providing bad or invalid credentials via `new Credentials(...)`, the SDK will attempt to auth via GitHub REST API, which will return a 401. Then the SDK will return an unhandled exception that looks something like this:

`Unhandled exception. Octokit.AuthorizationException: Bad credentials`

You should be able to catch that exception and respond accordingly. Otherwise, the method `new Credentials(...)` will return auth credentials that you can assign to `client.Credentials`

Consider the following:

```
    var githubClient = new GitHubClient(new ProductHeaderValue("my-octokit-app"));

    try {
      var credentials = new Credentials("token");
      if (credentials != null) {
          githubClient.Credentials = credentials;
      }
      // Error is thrown here when attempting to get a resource
      var repos = await githubClient.Repository.GetAllForOrg("octokit");
    }
    catch (System.Exception ex) {
      var errorToDoSomethingWith = ex.Message;
      throw;
    }
```

Note also that there are only 4 overloads in octokit for [credentials](https://github.com/octokit/octokit.net/blob/main/Octokit/Http/Credentials.cs):

```
    public Credentials(string token);
    public Credentials(string login, string password);
    public Credentials(string token, AuthenticationType authenticationType);
    public Credentials(string login, string password, AuthenticationType authenticationType);
```

And Octokit.net supports four types of auth:

```
Anonymous,
Basic,
Oauth,
Bearer
```

Let me know if this helps or if I missed the intent of your question!

**Comment by nickfloyd** [comment]
Hey @Sjaiswal08,

I am going to close this, assuming that it addressed your question.  If you still need help please feel free to reopen the issue.
