### ISSUE TITLE
[FEAT]: Mechanism to use custom filters on the API

### ISSUE THREAD

**Issue by bgavrilMS** [octokit/octokit.net#2679]
### Describe the need

I'd like to fetch all (open and closed) issues since the start of 2023. I can do this via curl by constructing an URI request like: 

`https://api.github.com/repos/AzureAD/microsoft-authentication-library-for-dotnet/issues?state=all&since=2023-01-01`

But I can't seem to achieve the same from the .NET API. Is there a way for me to specify the `state` and `since` parameters? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @bgavrilMS, you should be able to do this using [IssueRequest](https://github.com/octokit/octokit.net/blob/ddb66ed7120a9f9e45c3bf13b006173b6ff4cf86/Octokit/Models/Request/IssueRequest.cs#L13)

It contains `since` and `state` properties to allow you to make a request via [IssuesClient](https://github.com/octokit/octokit.net/blob/main/Octokit/Clients/IssuesClient.cs#L126)

Have a look at the references and let me know if that's what you're looking for.

**Comment by bgavrilMS** [comment]
Got it, thanks!
