### ISSUE TITLE
[BUG]: Octokit.net cannot handle mannequin users

### ISSUE THREAD

**Issue by asklar** [octokit/octokit.net#2687]
### What happened?

A long time ago, Python had its own bug database/git repository called BPO. Then they migrated to github. As part of the migration, they decided to not migrate their users and instead create "mannequin" accounts. Somehow this became a feature in GitHub: [What on Earth is a “mannequin”?](https://devguide.python.org/triage/github-bpo-faq/index.html#what-on-earth-is-a-mannequin)

We have a tool that uses octokit.net and looks through PRs/Issues. Our tool found a PR in the python/cpython repo, which was created by one of these mannequin accounts:
https://github.com/python/cpython/issues/50246

Octokit.net does not know how to deal with these as they don't represent real users.

![image](https://user-images.githubusercontent.com/22989529/226470814-1aa36bc6-7725-4c1d-bce6-4d4003c27918.png)

### Versions

octokit.net 5.0.0

### Relevant log output

```shell
![image](https://user-images.githubusercontent.com/22989529/226470814-1aa36bc6-7725-4c1d-bce6-4d4003c27918.png)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @asklar, thanks for reaching out.  You are correct; the [enterprise importer](https://docs.github.com/en/migrations/using-github-enterprise-importer/completing-your-migration-with-github-enterprise-importer/reclaiming-mannequins-for-github-enterprise-importer) uses them as placeholders.

They do exist as enums (mostly) in the [GitHub OpenAPI specification](https://github.com/github/rest-api-description/tree/main/descriptions) and therefore are valid values that can be passed into and out of our SDK - Octokit.net simply doesn't have this value implemented yet.  This is because this particular SDK is hand built (we are working on generative solutions for it though). Let me know if this is something that you'd be interested in adding to whichever endpoint/model you are using.

I'll also add the up for grabs label to let the community know that they can pick it up as well.

**Comment by asklar** [comment]
thanks @nickfloyd - I'm building an app that uses octokit.net, call some API to fetch some details about a repo that the user asks for, and it just so happens they provided the python repo. There seems like there isn't much from the app's perspective that we can do to ignore/skip issues that have a mannequin user in them, it just fails the whole operation :-/

**Comment by asklar** [comment]
thanks @kfcampbell !! 🥳
