### ISSUE TITLE
[FEAT]: Expand Environments client for secrets and variables

### ISSUE THREAD

**Issue by timheuer** [octokit/octokit.net#2752]
### Describe the need

On the Environments client it should expose the ability for retrieving the Secrets and Variables for each Environment	

### SDK Version

Octokit.net 7.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by drewid** [comment]
Definitely have an interest in this, as the repository secrets just aren't granular enough.  Plan on using those in conjunction with Azure Key Vault to have smooth GitHub to Azure deployment environment/branch/slot-related secrets.

**Comment by drewid** [comment]
@timheuer @kfcampbell @nickfloyd - I looked at it and have done the core work on this along with tests.  Have been able to get all, get specific, upsert, and delete environment secrets to all work.

What is the recommended method for contributing, create branch, or fork to pull back in?  Not seeing a branch option.

**Comment by drewid** [comment]
@timheuer @kfcampbell @nickfloyd checking back in on how you want me to proceed.  Have the code changes done.

**Comment by drewid** [comment]
I have also added the code changes for environment variables as well.

**Comment by nickfloyd** [comment]
> [@timheuer](https://github.com/timheuer) [@kfcampbell](https://github.com/kfcampbell) [@nickfloyd](https://github.com/nickfloyd) checking back in on how you want me to proceed. Have implemented, tested and now have working live code changes done for both environment secrets and environment variables.

Hey @timheuer Apologies for the delay on getting back to you and thanks for the follow up.  Here are our contributing [guidelines](https://github.com/octokit/octokit.net/blob/main/CONTRIBUTING.md) and some [conventions](https://github.com/octokit/.github/blob/main/community/commits_pr_conventions.md) that we use.  

The basics are - create a fork, make your changes, write some tests, then create a PR.  Because we serve more than 2000 external contributors across 75 different repos we have a process that we follow to help us prioritize things as well, have a [look](https://github.com/octokit/.github/blob/main/community/prioritization_response.md) if you get the chance.

Most importantly, thank you for becoming part of the Octokit community!  We cannot build the tools and help the millions of developers that we do without folks like you!  So thank you ❤ 

Side note, I am going to review our contribution docs and see if I cannot simplify things there - please let me know if you have any feedback on those docs so that we can make them better for everyone!

**Comment by drewid** [comment]
Thanks @nickfloyd.

Per the conventions doc I will create a PR with the following for review:

feat: Adds Environment Secrets & Variables
