### ISSUE TITLE
[BUG]: ProcessWorkflowRunWebhookAsync not being called after upgrade to 2.0.0 or 2.0.1

### ISSUE THREAD

**Issue by PavelBansky** [octokit/octokit.net#2755]
### What happened?

After upgrading from 1.5.2 to 2.0.1 the webhooks are no longer processed.
I'm specifically using `ProcessWorkflowRunWebhookAsync`

`protected override Task ProcessWorkflowRunWebhookAsync(WebhookHeaders headers, WorkflowRunEvent workflowRunEvent, WorkflowRunAction action)`

I can see in the AppInsight that webhook calls are being received by the app, but `ProcessWorkflowRunAsync` is not being called.

After downgrading back to 1.3.5 everything is working fine

### Versions

Octokit.Webhooks 2.0.1
Octokit.Webhooks.AspNetCore 2.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PavelBansky** [comment]
More investigation:
I was able to successfully upgrade to `1.5.2`

Upgrading from `1.5.2` to '2.0.0` will cause application to not call `ProcessWorkflowRunAsync`

**Comment by nickfloyd** [comment]
Hey @PavelBansky thanks for letting us know about this.  Let us know if this is something that you might be interested in picking up.  I have added the up for grabs label and placed it in ready so that anyone can grab this.

My main concern is that the version you're trying to use is 5 major versions behind and that v2.0.0 dropped support for .NET v4.6 because of EoL support.

Have you tried jumping up to the latest version - I know sometimes that's not possible because of the vast amount of changes.  

Just as a heads up, we do have a .NET package devoted to [webhooks](https://github.com/octokit/webhooks.net) as well.
