### ISSUE TITLE
[BUG]: CompareResults.File limited to 300 maximum files?

### ISSUE THREAD

**Issue by CaseyChester** [octokit/octokit.net#2763]
### What happened?

The documentation for RepositoryCommitsClient.Compare function indicate that all files included in the compare are returned in the first paginated response. As far as I can tell, the maximum number of files returned is 300, which are returned in the first response, but there is no way to retrieve the remainder of the files for comparisons that include more than 300 files. Not sure if this is a bug or a limitation 'by design'.

### Versions

Octokit.net version 7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @CaseyChester thanks for reaching out! ❤️ 

If I am understanding you're use case correctly, you should be able to use the following interface and pass in APIOptions:

`Task<CompareResult> Compare(string owner, string name, string @base, string head, ApiOptions options);`

So it might look something like in a loop or some sort of iteration:

```
var options = new ApiOptions
 {
     PageSize = 100,
     PageCount = 1,
    StartPage = 1
};

var commits = await  client.Compare(string "owner", "repo_name", "base", "head", options);
```

Also, the REST API docs on comparing commits says the limit is [250](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#compare-two-commits). I'll let our docs folks know that you are seeing 300 so that we can get that corrected and up to date.

Let us know if this approach works for you!

**Comment by dbalatero** [comment]
@nickfloyd I've seen the pagination thing in multiple responses on this issue, but from my testing, it seems that the pagination applies to _commits_, not _files_.

If you have a commit range with only 2 commits in it (which is under the 100 per page limit), but 5000 files:

- page 1 will return 2 commits, and 300 max files
- page 2 will return 0 commits, because there aren't more than 100, and 0 files

**Comment by shhdgit** [comment]
> @nickfloyd I've seen the pagination thing in multiple responses on this issue across various GitHub-related repos, but from my testing, it seems that the pagination applies to _commits_, not _files_.
> 
> If you have a commit range with only 2 commits in it (which is under the 100 per page limit), but 5000 files:
> 
> * page 1 will return 2 commits, and 300 max files
> * page 2 will return 0 commits, because there aren't more than 100, and 0 files

Same result here.
