### ISSUE TITLE
Not all tags are equal

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#295]
Just got bitten by this one, not sure what sort of solution it requires - would love some feedback.

http://git-scm.com/book/en/Git-Basics-Tagging#Creating-Tags

Repro:

```
var client = new GitHubClient(new ProductHeaderValue("MyCoolApp"));
var releases = await client.Release.GetAll("octokit", "octokit.net");

var mostRecentTag = releases[0].TagName;

// this succeeds 
var referenceName = "tags/" + mostRecentTag;
var reference = await client.GitDatabase.Reference.Get("octokit", "octokit.net", referenceName);

// this throws a NotFoundException
var tag = await client.GitDatabase.Tag.Get("octokit", "octokit.net", mostRecentTag);
```

A couple of possible solutions:
- a better error message explaining that the tag might not exist because it's a lightweight tag, with a pointer to some helpful documentation
- internally the TagClient could call the reference API if it finds a 404 - but this feels bad for several reasons

**Comment by SeanKilleen** [comment]
Bumping this because it's pretty old.

I'm thinking it would make sense to close this in lieu of a new ticket referencing this and suggesting the documentation changes that came from @shiftkey's comment: https://github.com/octokit/octokit.net/issues/295#issuecomment-32185849

Let me know if that's the right approach here; I'm happy to write up the new ticket.

**Comment by shiftkey** [comment]
@SeanKilleen yeah, let's just document it rather than trying to be too clever here. Happy to discuss in a new issue.
