### ISSUE TITLE
[FEAT]: Will GitHub Classroom Api be supported?

### ISSUE THREAD

**Issue by Cai1Hsu** [octokit/octokit.net#2967]
### Describe the need

I am teaching a group of students with GitHub Classroom and I was trying to build an app to manage assignments and other sorts of things. octokit's API has helped me build my app easier and faster, but I was disappointed that this library does not support GitHub Classroom. There are only 6 APIs so I assume it wouldn't be hard to implement.

### SDK Version

Octokit.net 13.0.1

### API Version

REST API 2022-11-28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @Cai1Hsu, 

Thanks for reaching out.  You are correct.  Maintaining this SDK is a manual task, which is why we've made the[ move to a generated SDK](https://github.blog/news-insights/product-news/our-move-to-generated-sdks/).  You'll find that our new [generated .NET SDK](https://github.com/octokit/dotnet-sdk/tree/main/src/GitHub/Classrooms) has more feature and almost 100% of all GitHub REST APIS.

While octokit.net is still maintained our focus has shifted to the new approach for exactly the reason you mentioned above.  

Going forward our community has been mostly driving the additions of APIs to this SDK while we've been focused on building out the [other](https://github.com/octokit/dotnet-sdk).

Please feel free to add the APIs the this SDK or give the newer one a shot.

**Comment by Cai1Hsu** [comment]
thanks, i didn't know this before.
