### ISSUE TITLE
Immutable over ReadOnly.

### ISSUE THREAD

**Issue by Zoltu** [octokit/octokit.net#678]
A recent commit changed many of the models to be ReadOnly.  I am a huge fan of immutability and this is a good step in the right direction.  I would encourage, however, immutability over ReadOnly because it asserts more about the contract between the library and the library user.

```c#
public class Person
{
    public readonly String FirstName;
    public readonly Int32 Age;
}
```
```c#
public class Person
{
    public String FirstName { get; private set; }
    public Int32 Age { get; private set; }
}
```

In the first case, the library is asserting to the user that the attributes of Person will not change.  In the second case, the library is only denying the user the ability to change the object, it is not guaranteeing that the library won't change the object out from under the user at some point.

In the case of Octokit as it stands now, the user can likely reason safely that the library isn't changing the object out from under the user.  However, as Octokit grows and further abstractions are created it becomes more and more difficult for a user to make such an assertion, which makes it difficult for the user to reason about their own code.

**Comment by Haacked** [comment]
I'm a fan of immutability too, but I think using `readonly` fields instead of properties will introduce more problems than it solves.

First of all, I think we want to stick with properties. Data binding infrastructure in much of .NET depends on properties, not fields. It _might_ not make sense to bind to these objects, but I don't want to prevent it. Also, it gives us the freedom to change the implementation of the property in the future should we ever have a good reason to do so.

Also, a `readonly` field currently doesn't guarantee immutability. It just so happens via a fluke of implementation that you _can_ set a `readonly` field via reflection, but as [Eric Lippert points out](http://stackoverflow.com/questions/934930/can-i-change-a-private-readonly-field-in-c-sharp-using-reflection#comment743456_934944)...

> I note also that just because you can in some implementation today does not mean that you can on every implementation for all time. I am not aware of any place where we document that readonly fields must be mutable via reflection. As far as I know, a conforming implementation of the CLI is perfectly free to implement readonly fields such that they throw exceptions when mutated via reflection after the constructor is done

The point here is while we can't rely on this behavior, it is possible today negating the immutability guarantee. Our current implementation is every bit as immutable as one with `readonly` fields.

Lastly, if the implementation ever did change, it would considerably complicate our deserialization of these objects.

For all these reasons, I would rather stick with the way we currently do them. Until the language supports `immutable` as a first class construct, the best we can do is provide a "verbal" guarantee of immutability. :smile:
