### ISSUE TITLE
SubscribersCount is zero

### ISSUE THREAD

**Issue by christophwille** [octokit/octokit.net#735]
![zerocount](https://cloud.githubusercontent.com/assets/344208/6430593/fe04319c-c010-11e4-9b12-a184364cb4cc.png)

Code to verify is in the WpaGhApp repository (a Windows Phone 8.1 app). You can put a breakpoint on the following line (and check the repos variable):

https://github.com/christophwille/wpaghapp/blob/master/Source/WpaGhApp/ViewModels/Main/RepositoriesViewModel.cs#L43

Note that you first have to register an application with GitHub and enter the credentials here:

https://github.com/christophwille/wpaghapp/blob/master/Source/WpaGhApp/GitHub/GhOAuthConfiguration.cs

**Comment by shiftkey** [comment]
`subscribers_count` is no longer returned from the API for this endpoint. The only two counters we return here are `stargazers_count` (the number of users who have starred a repo) and `watchers_count` - which we are no longer showing because it's not correct and to be deprecated as per #699

![screen shot 2015-03-02 at 12 50 12 pm](https://cloud.githubusercontent.com/assets/359239/6434518/b6e99a5c-c0da-11e4-9ac5-c8329f2395b1.png)

The right way to retrieve the watchers for the repository is to use the [Watching](https://developer.github.com/v3/activity/watching/) API:

```
var client = new GitHubClient(new ProductHeaderValue("testing-wp-octokit"));
client.Credentials = new Credentials("...");
var watchers = await client.Activity.Watching.GetAllWatchers("christophwille", "viennarealtime");
```

@christophwille let me know if I've missed anything
