### ISSUE TITLE
Suggestion: Implement timeout overloads for all asynchronous methods

### ISSUE THREAD

**Issue by Aaronontheweb** [octokit/octokit.net#744]
Related to #48.

I just finished writing the last unit of our [Akka.NET Bootcamp](https://github.com/petabridge/akka-bootcamp/tree/master/src/Unit-3) (self-paced learning course via Github for [Akka.NET](https://github.com/akkadotnet/akka.net),) which has students combine Octokit.NET and Akka.NET to find similar repositories based on overlapping stargazers.

The Octokit SDK is super cool and I think the folks going through our bootcamp will be really excited to get a chance to use it, so thanks for making it!

However, one of the things I found a little frustrating was that there doesn't seem to be any options for timing out an Octokit call - some of the `_gitHubClient.Activity.Starring.GetAllForUser(starrer)` calls we make take an exceptionally long time to return. Minutes. And in some cases the calls never get completed and silently fail.

Could very well be an issue with how we're using the SDK, but regardless I'd like to have the option to time out individual requests. `TaskCancelledExceptions` are a nuisance, but they're still better than not hearing anything back at all :p 

It looks like your internals already lay much of the groundwork for supporting it - would you consider adding an optional `TimeSpan?` parameter to all methods returning a `Task` for specifying explicit per-request timeouts?

I see that in #587 you added the ability to set a default timeout across the entire connection - glad I know about it now but it's not obvious or easy to find :p

**Comment by shiftkey** [comment]
@Aaronontheweb thanks for the feedback! When I saw the tweet earlier today I was really excited to see what was on the way!

> However, one of the things I found a little frustrating was that there doesn't seem to be any options for timing out an Octokit call - some of the _gitHubClient.Activity.Starring.GetAllForUser(starrer) calls we make take an exceptionally long time to return. 

Yeah, this is something I've been putting off and pushing out for a while.

Here's a TL:DR on the situation as it stands:

 - the API support pagination using the [Link](https://developer.github.com/v3/#link-header) header whenever sets of results are returned
 - Octokit will auto-follow the pagination results until it's reached the end of the set
 - the end user will get the entire result set

And this sucks for anything involved with wanting to control the # of pages returned or cancel an in-flight request.

> And in some cases the calls never get completed and silently fail.

If you can recreate this (quite often it's related to a specific user account) I'd love to investigate this further.

> Could very well be an issue with how we're using the SDK, but regardless I'd like to have the option to time out individual requests.

Yep, there's a couple of options at hand - and making it all work in an uncomplicated way is something I'll need to start working on Real Soon. With Rx, disposing the subscription is generally considered The Right Way to do that, so I'm not really worried about that scenario right now.

A couple of ideas (one or the other or both could land in the framework):

 - the pagination work in #740 would help you constrain how much data you want. The initial feedback I've got on this seems promising, but it's a big change to everything so I don't want to rush it.
 - `HttpClient` supports providing a `CancellationToken` when it's making a request - perhaps we should have overloads on the `GetAll` operation so that you can cancel the in-flight requests (this should also kill the pagination, but I need to confirm this). This feels better than reinventing the wheel.

I'd love to hear more about your scenario (is pagination better than cancellation?) so I can focus things in the short-term.

> I see that in #587 you added the ability to set a default timeout across the entire connection - glad I know about it now but it's not obvious or easy to find :p

That would work for a single request - we added this because uploading release assets takes a while - but for our scenario where we reset the timer for each request (due to pagination) it probably won't be enforced.

**Comment by Aaronontheweb** [comment]
> HttpClient supports providing a CancellationToken when it's making a request - perhaps we should have overloads on the GetAll operation so that you can cancel the in-flight requests (this should also kill the pagination, but I need to confirm this). This feels better than reinventing the wheel.

This is my preference - feels idiomatic :)

> If you can recreate this (quite often it's related to a specific user account) I'd love to investigate this further.

That's what it looks like - I didn't dig in with something like Fiddler to see what was happening at the HTTP level but we weren't receiving any rate limit exceptions or anything like that. If I had to guess, these long-running queries were for users who had starred a large number of repositories. The "Robert Scoble" effect for Github :p 

In our scenario cancellation is the preferred way of doing it - being able to mark N number of requests as failed and return partial results from the operations that were successful is what's most appropriate in our specific scenario, although it's worth noting that our scenario is for educational purposes only :p 

> @Aaronontheweb thanks for the feedback! When I saw the tweet earlier today I was really excited to see what was on the way!

We announced it to our attendees (who've done the previous two units over the past couple of weeks) this morning - seems like a hit so far: https://twitter.com/petabridge/status/575371782741364736

**Comment by shiftkey** [comment]
I'm feeling that #760 is a more familiar option for developers than cancellation tokens (and more useful in general):

```
[IntegrationTest]
public async Task CanPageRepositories()
{
    var github = Helper.GetAuthenticatedClient();

    var options = new ApiOptions { PageSize = 10, PageCount = 1 };
    var repositories = await github.Repository.GetAllForCurrent(options);

    Assert.Equal(10, repositories.Count);
}
```

Once that lands on `master` I'll close this out.

Let me know if you have any other thoughts on either approach.
