### ISSUE TITLE
Get issues filtered by labels

### ISSUE THREAD

**Issue by alandball** [octokit/octokit.net#761]
When specifying parameters when getting issues, it is easy to specify by which state to filter, but not by which labels. The State has a getter and setter, but the collection of labels only has a getter.

Here is an example of my code
```
_gitHubclient.Issue.GetForRepository(
    "Org name",
    "Repo name",
    new RepositoryIssueRequest
    {
        State = ItemState.Closed,
        Labels = new[]
        {
            new Label { Name = "Client Name" }
        }
    }
)
```

I understand the spec to say that filtering by labels is allowed: https://developer.github.com/v3/issues/#list-issues-for-a-repository

This is from the dll/metadata when I hit F12 in VS: public Collection<string> Labels { get; }, but when I look at the source: public Collection<string> Labels { get; private set; }

**Comment by shiftkey** [comment]
The public setter has been removed due to it clashing with an [FxCop rule](https://msdn.microsoft.com/en-ca/ms182327.aspx). I thought I had an integration test to demo this specific endpoint, but I don't.

The collection is already instantiated in [the constructor](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/IssueRequest.cs#L16) so it's just a matter of adding elements to the collection:

```
var request = new RepositoryIssuesRequest { State = ItemState.Closed };
request.Labels.Add(new Label { Name = "Client Name" });
_gitHubclient.Issue.GetForRepository(
    "Org name",
    "Repo name",
    request)
```

If you feel up to improving this API, I can reopen this issue and we can discuss it further...

**Comment by alandball** [comment]
Hi, thanks for the quick response. The .Add(), why create a new label? It takes in a string, so just putting the label name is good, yeah?

**Comment by shiftkey** [comment]
> The .Add(), why create a new label? It takes in a string, so just putting the label name is good, yeah?

Gah, my bad. This is what happens when you reply to things late at night.
I'll edit that snippet above to reflect this.
