### ISSUE TITLE
specifying a proxy when connecting to a GitHub Enterprise server

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#809]
Found this while looking at #808.

It's currently rather hard to do cry: (you need to specify _all_ the parameter), and I'm not sure if anyone depends on this.

Please comment on this if it impacts you, and I'll adjust it in my priority queue. See #781 for other discussions about how Octokit plans to adapt it's usage of `HttpMessageHandler` to support more flexibility...

**Comment by squeakyD** [comment]
The reason why this doesn't work is because what I need to do is pass in the GHE URL, i.e.

`var client = new GitHubClient(new ProductHeaderValue("my-cool-app"), new Uri("https:// .... "));`

However only the way you can currently add a proxy in code is:

`
 var proxy = new WebProxy(new Uri("http://proxyarray.service.group:8080"), true);
            proxy.Credentials = CredentialCache.DefaultCredentials;
            IHttpClient httpClient = (IHttpClient)HttpMessageHandlerFactory.CreateDefault(proxy);
          
            var connection = new Connection(new ProductHeaderValue("my-cool-app"),
                new HttpClientAdapter(() => HttpMessageHandlerFactory.CreateDefault(proxy)));
            var client = new GitHubClient(connection);

The problem is that there is no constructor that can take an IConnection and a URL.

**Comment by BanksySan** [comment]
Is there a solution for this yet?  There doesn't seem to be a way to use a proxy and supply credentials.
