### ISSUE TITLE
DateTimeOffset MinValue in URL parameter results in Error

### ISSUE THREAD

**Issue by thedillonb** [octokit/octokit.net#827]
Just a heads up, as this doesn't seem to have anything to do with the client but more with GitHub, but it makes it looks like a serialization issue in Octokit.Net. It looks like objects that are of type `DateTimeOffset` and are defaulted to `MinValue` are no longer working due to an issue on the server.

`Octokit.NotificationsRequest` contains a `Since` attribute which is defaulted to `DateTimeOffset.MinValue` which results in a serialized URL: `https://api.github.com/notifications?all=false&participating=false&since=0001-01-01T00%3A00%3A00Z`

Unfortunately, GitHub is now responding with the following:

```
{
    "message": "The since parameter needs to be in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ",
    "documentation_url": "https://developer.github.com/v3/#schema"
}
```

The error in Octokit.Net looks like an issue with the serializer but is actually server side. Adjusting the `since` to something closer to the current time results in success:

`https://api.github.com/notifications?all=false&participating=false&since=2001-01-01T00%3A00%3A00Z` works fine.

**Comment by shiftkey** [comment]
@thedillonb thanks for the info, I'll pass it on to the API team

**Comment by shiftkey** [comment]
Rather than go through all the hoops for duplicating this internally, I'll just cc @pengwynn here and bug him in chat when I wake up tomorrow:

 - `since=0001-01-01T00%3A00%3A00Z` isn't considered a valid date under `/notifications`
 - `since=2001-01-01T00%3A00%3A00Z` works fine
 - probably just some edge case thing that was introduced recently

**Comment by Haacked** [comment]
@shiftkey Hmm, should we simply omit "since=" if the value is MinValue?

**Comment by shiftkey** [comment]
@haacked possibly, but I think that just hides the problem for scenarios where the range is actually invalid...

**Comment by dampir** [comment]
I know it is the old question, but have some info about it.

> Rather than go through all the hoops for duplicating this internally, I'll just cc @pengwynn here and bug him in chat when I wake up tomorrow:

since=0001-01-01T00%3A00%3A00Z isn't considered a valid date under /notifications
since=2001-01-01T00%3A00%3A00Z works fine

> probably just some edge case thing that was introduced recently

It is not exactly a corner case, because issue arises from dates in range from 0001-01-01 00:00:00 to 0999-12-31 23:59:59 i.e. when year is less that 1000 (YYYY < 1000). So, the next query not work too:

`
curl --user "user:pass" "https://api.github.com/notifications?all=false&participating=false&since=0999-12-31T23%3A59%3A59Z"
`

**Comment by shiftkey** [comment]
@dampir I do like enforcing some validation within Octokit to catch this, with a sensible error message delivered to the caller
