### ISSUE TITLE
.Net 4.0/Xamarin compatibility

### ISSUE THREAD

**Issue by Pilchard123** [octokit/octokit.net#843]
According to http://haacked.com/archive/2013/06/24/platform-limitations-harm-net.aspx/, the reason that octokit.net doesn't support .Net 4.0 is because of platform restrictions on some of the libraries that are used.

According to http://blogs.msdn.com/b/dotnet/archive/2013/11/13/pcl-and-net-nuget-libraries-are-now-enabled-for-xamarin.aspx, those restrictions have been lifted. Would it be possible to make it compatible with .Net 4.0/Xamarin now, or have I misunderstood one (or both) of those posts?

**Comment by shiftkey** [comment]
The platform restrictions were actually related to the Mono* support - we weren't allowed to use those packages on non-Windows OSes. The Mono project for Octokit was/is still targeting .NET 4.5.

We drew the line there as our "baseline" for a couple of reasons:

 - The Task Parallel Library implementation received a lot of love in .NET 4.5, and is noticeably faster. We use tasks *everywhere* in Octokit, so we were happy as pigs in mud.
 - Portable Class Library support (even though it wasn't there at the time) had a sweet spot `Profile259` which correlated to .NET 4.5 across all the platforms.
 - Dropping down to a PCL profile which included .NET 4.0 had a very limited subset of APIs - we'd have to re-implement even more.

I'm not really interested in supporting Yet Another Platform™ because this adds pain for new contributors as well as myself - I know of some people who have forked and are building Octokit from source, so perhaps that's an option here? 

And .NET 4.5 support is ending at the end of 2015, so I'll be taking some time out to review and simplify the platforms I target.

Let me know if you have any other questions on this.

**Comment by Pilchard123** [comment]
4.5 support ending? Good to know, that'll make things much easier for me as well.

**Comment by shiftkey** [comment]
> 4.5 support ending? 

It's outlined here: https://support.microsoft.com/en-us/gp/framework_faq?wa=wsignin1.0

> Microsoft recommends that customers and developers using .NET Framework 4, 4.5, or 4.5.1 complete the in-place update to .NET Framework 4.5.2 by January 12, 2016 to continue receiving technical support and security updates.
