### ISSUE TITLE
Trying to "GetAll" commits

### ISSUE THREAD

**Issue by Nasicus** [octokit/octokit.net#858]
Hi - I'm really not sure if this is the right place, but I don't know where else to ask such a question, so  feel free to point me to another place and to close this issue if this is indeed not the right place.

I have the following situation:

My goal is to get all commits from a repository.

I started by installing the NuGet package `Octokit`, however I couldn't find a direct way to get all commits from a repository there. So I had a look at the source code and saw that there is another project - namely `Octokit.Reactive`. I then installed this package via NuGet and wrote the following code:

      var github = new GitHubClient(new ProductHeaderValue("MyApp"));
      var observableClient = new ObservableGitHubClient(github);
      GitHubCommit initialCommit = await observableClient.Repository.Commits.GetAll("FooBarUser", "FooBarRepo");

If I execute my application I can see (via fiddler) that all commits are retrieved. However I don't understand how I can "traverse" through these commits in the result I retrieved in my code.The `initialCommit` which I retrieved is indeed the initial commit of the repository - but how do I "get to" all other commits?

Also is it even correct, that I installed `Octokit.Reactive`? If so should the documentation in the `readme.md` be updated?

Greetings
Patrick

**Comment by khellang** [comment]
@Nasicus You should be fine using the regular `Octokit` package as well, the `Octokit.Reactive` package just wraps the former with `IObservable<T>` overloads.

The problem is that you're awaiting an `IObservable<GitHubCommit>`, which will return the *last* result. See [Rx and Await: Some Notes](http://log.paulbetts.org/rx-and-await-some-notes/).

If you really want to use the reactive API, you should correctly subscribe to the observable, using the `Subscribe` method. Its callback argument will be called for each `GitHubCommit` in the repository.

**Comment by Nasicus** [comment]
@khellang Thanks for this fast and good answer!

Looks like I'm a complete idiot - I have no idea how I could miss that the `GetAll` method is also available within the `Octokit` project and not only in `Octokit.Reactive`.... (I was so sure it isn't...)

Didn't know that part about Rx and Await  - so at least I learned something new there.

Anyway thanks again.
