### ISSUE TITLE
Client Interactive Token Acquisition

### ISSUE THREAD

**Issue by whoisj** [octokit/octokit.net#859]
Is there a way to perform client-side interactive token acquisition?

For example, is there a way from within an app to acquire a personal access token scoped to say pull request viewing from the command line or from a Windows Form application?

I'm not seeing an obvious way to do so.

Any help here would be much appreciated. Thanks!

**Comment by shiftkey** [comment]
@haacked did a demo of this for an ASP.NET app https://github.com/Haacked/octokit-oauth-demo

I've not looked at doing this for a client-side flow, but the current advice is described [here](https://developer.github.com/v3/oauth/#non-web-application-flow).

**Comment by whoisj** [comment]
Thanks - looks like a manual setup then and not something Octokit handles. Is that a correct assessment?

**Comment by Haacked** [comment]
I think @shiftkey misunderstood the question. If I understand correctly, you want to __create__ a personal access token with a specific scope using Octokit.

That is possible using the [authorizations API](https://developer.github.com/v3/oauth_authorizations/).

In Octokit, you'd do something like this:

```csharp
var github = new GitHubClient(new ProductHeaderValue("MyAmazingApp"));
var newAuthorization = new NewAuthorization("Notes for this", new [] { "public_repo" });
var authorization = await github.Authorization.Create(client, clientSecret, newAuthorization);
Console.WriteLine(user.Followers + " folks love the half ogre!");
```

That creates an authorization with the scope that...

> Grants read/write access to code, commit statuses, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.

The list of scopes is located here: https://developer.github.com/v3/oauth/#scopes

I don't see one that limits scope to just viewing pull requests.

**Comment by Haacked** [comment]
Ah, I misunderstood too! So the code I showed creates an Application Authorization. It's an OAuth token that authorizes an application to perform actions. You can see these listed here: https://github.com/settings/applications

If you require a Personal Access Token (listed here https://github.com/settings/tokens) then you'll need to go through the [Web Flow](https://developer.github.com/v3/oauth/#web-application-flow) as @shiftkey mentioned.

Since that flow is an OAuth token exchange workflow, there's really not a good way for Octokit to just handle it for you.

We could probably implement some libraries for WPF apps to initiate the web flow at some point. I think that'd be a nice to have and would at least make this much simpler for people to implement.

**Comment by whoisj** [comment]
@Haacked honestly, I'm looking to do this with client-side automation so these would be in a command-line or powershell environment. I'd have access to interactive sessions however, so I suppose WPF would be acceptable. I think the biggest hurdle will be 2fa.

Right now I'm looking at hitting http://api.github.com/v3/authorization, catching a failure, look at the header for 2fa failure codes, and then asking for the 2fa bit. In theory, with that - I should be able to acquire a token, store it, and reuse it as needed.

Sounds about right?

**Comment by Haacked** [comment]
> @Haacked honestly, I'm looking to do this with client-side automation so these would be in a command-line or powershell environment.

Oh, in that case why would you need to create an access token? After all, you have a chicken and egg problem here. Your script, in order to create a token, would need some credentials to have the authorization to create the token.

So instead of giving your script a username and password, manually create an authorization token once, and give that to your script.

Perhaps I'm missing something.

> Right now I'm looking at hitting http://api.github.com/v3/authorization, catching a failure, look at the header for 2fa failure codes, and then asking for the 2fa bit. In theory, with that - I should be able to acquire a token, store it, and reuse it as needed.

Yep, that's about right.

In `Octokit.Reactive` we have a `GetOrCreateApplicationAuthentication` method that handles part of this flow for you. You can pass in a `Func` that gets called if the initial request fails because of a 2fa error.

We don't have a `Task` based version yet, but I'd love to add one at some point. That code was pretty much pulled from GitHub for Windows which is all Rx based.
