### ISSUE TITLE
Upload to Github releases stopped working

### ISSUE THREAD

**Issue by forki** [octokit/octokit.net#894]
We use "Github releases" in many projects and we use Octokit to upload stuff to the releases page. This stopped working last week.

![image](https://cloud.githubusercontent.com/assets/57396/9871632/3a0b5ce0-5b95-11e5-8ca6-62fa0c012df5.png)

I'm seeing OctoKit.ApiExceptions.

I created a repro sampe at https://github.com/forki/TestUpload.

* Fork the project (maybe to a private space)
* Replace your account and repro settings in the build.fsx (see https://github.com/forki/TestUpload/blob/master/build.fsx#L13)
* run build.bat on windows.

As I said above this worked before.

**Comment by naveensrinivasan** [comment]
The reason for the failure is because the release api has an optional argument called `label` along with `name` which is required
https://developer.github.com/v3/repos/releases/#upload-a-release-asset

The releaseclient code `UploadAsset` method https://github.com/octokit/octokit.net/blob/9198f80e5d1880344040d5652645000b151cc071/Octokit/Clients/ReleasesClient.cs#L161 invokes the `ExpandUriTemplate` method https://github.com/octokit/octokit.net/blob/6aa323c8ffb26cdf5ac2721da72c169a1795e32f/Octokit/Helpers/StringExtensions.cs#L48 which does not expand the `name` parameter for the api which is required because it expects only one parameter which is the bug. 

![bug](https://cloud.githubusercontent.com/assets/172697/9891587/4905c5a6-5bd5-11e5-90b7-6aaffbe6dd79.png)


This is causing the api throw an error with `Invalid name for request` because request `name` was not provided in the call. 

Here is a sample code to recreate this issue



```
void Main()
{
	
	//replace the token, username,repositoryName
	var username = "naveensrinivasan";
	var token = "REPLACE_TOKEN";
	var repositoryName = "TestUpload";
	
	IReleasesClient _releaseClient;
	
	
	var stream = new FileStream(@"c:\temp\test.txt",System.IO.FileMode.Open);
	
	var github = new GitHubClient(new ProductHeaderValue("test"));
	github.Credentials = new Credentials(token);
	
	_releaseClient = github.Release;
	
	var releaseWithNoUpdate = new NewRelease("0.5") { Draft = true };
	var release = _releaseClient
		.Create(username, repositoryName, releaseWithNoUpdate)
		.Result;
	
	var newAsset = new ReleaseAssetUpload("hello-world.txt", "text/plain", stream, null);
	var result = _releaseClient.UploadAsset(release, newAsset).Result;
	
}

// Define other methods and classes here

```

**Comment by Haacked** [comment]
Great bug report @forki and great bug explanation @naveensrinivasan!

Are either of you interested in providing a PR to fix it?

**Comment by naveensrinivasan** [comment]
I can take this one.

**Comment by Haacked** [comment]
Excellent!

**Comment by forki** [comment]
So it's indeed a changed API and can be fixed in Octokit? Awesome. Can't
wait to "paket update nuget Octokit".

**Comment by naveensrinivasan** [comment]
This one should be closed.
