### ISSUE TITLE
Q: Can Octokit be made to work with an SSH agent?

### ISSUE THREAD

**Issue by adamralph** [octokit/octokit.net#930]
I.e. so that it just talks to my local SSH agent somehow and uses it's security gubbins to connect to the API?

Does this even make sense? As you can tell I'm a real expert on security.

**Comment by shiftkey** [comment]
Not really. As all the API calls for Octokit are done over HTTP/S we're kinda restricted to using the `Authorization` header.

**Comment by adamralph** [comment]
I see. I think that's the kind of answer I was expecting.

How about the HTTP credentials helper thingies? I don't use them myself (I'm an SSH man) but I don't suppose there's anything built into Octokit for talking to them? Or some other .NET wrapper somewhere you're aware of?

**Comment by shiftkey** [comment]
> How about the HTTP credentials helper thingies? 

These store the username/password/token somewhere on the local machine. Those would be usable in Octokit if you extract it, but this is often tied to the Git installation (Octokit doesn't depend on git.exe)

> I don't use them myself (I'm an SSH man) but I don't suppose there's anything built into Octokit for talking to them?

Afraid not, because they're two very different ways to authenticate:

 - SSH is session-based (connect to remote machine) versus HTTP's request/response model
 - with public-key infrastructure like this, keys can be managed better between actors
 - all this occurs on a different port (22 versus 80/443)

If you're looking for an alternative to providing your HTTP credentials, you could look at [Personal Access Tokens](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) or having an app create [authorizations](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization) on a user's behalf.

**Comment by adamralph** [comment]
> I don't use them myself (I'm an SSH man) but I don't suppose there's anything built into Octokit for talking to them?

I actually meant for talking to the HTTP credential helpers. I realise that SSH is something completely different to HTTP/HTTPS (and in that regard I'm not really sure why I asked the initial question).

I will indeed use a Personal Access Token because I'm using 2FA anyway.

Yeah, an app authorisation would be the right way to do this for an app I'm planning to distribute but this just a spiked console app for trying some things out. I kind of wanted to avoid having to put my personal access token into config/setting an environment variable/prompting for a password whilst I'm spiking this and I'm also switching machines as I travel around.

Anyway, the ROI on taking this further is not worth it. If this spike ever becomes a thing then it will end up as a windows service somewhere and we already have a general solution for storing credentials in that scenario.

Thanks for the answers!
