### ISSUE TITLE
How to use this package in ASP.NET Web forms?

### ISSUE THREAD

**Issue by A-Programmer** [octokit/octokit.net#962]
Hello.
I want to use this package in ASP.NET Web forms with old membership system, i just need to get a true or false answer form github that the username and password is correct or not, then i will register that user with that username and password.

**Comment by alfhenrik** [comment]
Hello,

You could do the following:
```
var client = new GitHubClient(new ProductHeaderValue("my-cool-app"));
var basicAuth = new Credentials("username", "password"); // NOTE: not real credentials
client.Credentials = basicAuth;
var userTask = await client.User.Current();
// Or if you don't do async/await
// var userTask = client.User.Current();
// var user = userTask.Result; <-- This call will fail if you passed bad credentials
```
The call to `client.User.Current();` will fail if the credentials are wrong.

Hope that helps!

**Comment by A-Programmer** [comment]
So where should i use ClientId and SecretId ?
And do you think its true to get Users username and password?
Is there any way to use this package to Authenticate user with GitHub login page?

**Comment by A-Programmer** [comment]
And one more question, can i use this structure for Google and Facebook?

**Comment by alfhenrik** [comment]
To use the GitHub login page to authenticate your users you should follow the OAuth web flow described here https://developer.github.com/v3/oauth/#web-application-flow
________________________________

**Comment by shiftkey** [comment]
@Haacked wrote a sample a while ago about using Octokit to do the OAuth dance (it's in an MVC app, but the concepts are the same). The [blog post](http://haacked.com/archive/2014/04/24/octokit-oauth/) and [sample code](https://github.com/Haacked/octokit-oauth-demo) should help you wire everything up.

As an aside, I'd strongly recommend against storing the user's credentials directly. OAuth was designed so that your application would have a token delegated to you by the user, which they can then revoke in the future if they feel the need.
